### ISSUE TITLE
my problems

### ISSUE THREAD

**Issue by dawoodiran** [SagerNet/SagerNet#102]
**Describe the bug**

**To Reproduce**

**Logcat**
Export it yourself :)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**

**Comment by dawoodiran** [comment]
i have this problems

when i select second option![Screenshot_۲۰۲۱-۰۵-۲۰-۱۸-۳۸-۰۵-۰۵۸_io.nekohasekai.sagernet.jpg](https://user-images.githubusercontent.com/34414138/118993449-c409a280-b99a-11eb-8b88-f4ea690db441.jpg)![Screenshot_۲۰۲۱-۰۵-۲۰-۱۸-۳۸-۲۴-۶۱۷_io.nekohasekai.sagernet.jpg](https://user-images.githubusercontent.com/34414138/118993539-d71c7280-b99a-11eb-9e02-deb1bac44d3f.jpg)
and close d when i select app mod
![Screenshot_۲۰۲۱-۰۵-۲۰-۱۸-۳۸-۵۱-۳۷۷_io.nekohasekai.sagernet.jpg](https://user-images.githubusercontent.com/34414138/118993810-12b73c80-b99b-11eb-8500-bb8f574dc2bb.jpg)

**Comment by dawoodiran** [comment]
![IMG_۲۰۲۱۰۵۲۰_۱۸۴۵۴۸.jpg](https://user-images.githubusercontent.com/34414138/118995753-a3dae300-b99c-11eb-8ce6-6b297896109a.jpg)
![IMG_۲۰۲۱۰۵۲۰_۱۸۴۷۰۴.jpg](https://user-images.githubusercontent.com/34414138/118995804-ab01f100-b99c-11eb-8e77-db8005478b5f.jpg)

closed when i select appvpn mod
![IMG_۲۰۲۱۰۵۲۰_۱۸۴۷۲۶.jpg](https://user-images.githubusercontent.com/34414138/118995920-c5d46580-b99c-11eb-8e93-96166377ea01.jpg)

**Comment by AkinoKaede** [comment]
[v2fly/domain-list-community](https://github.com/v2fly/domain-list-community) is not included Iranian domains.

**Comment by dawoodiran** [comment]
> [v2fly/domain-list-community](https://github.com/v2fly/domain-list-community) is not included Iranian dom 
I did not get please explain further

**Comment by AkinoKaede** [comment]
> > [v2fly/domain-list-community](https://github.com/v2fly/domain-list-community) is not included Iranian dom
> > I did not get please explain further

geosite:ir is not available.
