### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by klzgrad** [SagerNet/SagerNet#104]
1. Plugins require an Autostart permission in itself to work. This is not documented and the lack of permission is not immediately clear from the errors shown. Suggest better documentation so stuff can work the first time.
2. How do I update plugins without doing a lot of manual downloads? If managing all the plugin downloads is hard, be sure to have some update notifications for plugins.
3. Documentation, where is it? I don't want to keep guessing or read the fine source code. The following functionalities gave me trouble understanding as a first time user. Consider adding a few words at appropriate places.
    * Group. What does it do?
    * Security Advisory by Qv2ray. I don't use Qv2ray and don't know why do I need this.
    * Apps VPN mode, with off, on, bypass three options. They are confusing. The doc of VpnService has two modes, don't know why three are needed here.
    * Domain resolution strategy. Okay I'm totally lost here. What do these three options mean?
    * Enable traffic sniffing? For what? Sounds very bad for privacy. Is this the trick that recovers domain names from FakeDNS addresses?
    * DNS mode. I know, System and FakeDNS. What's remote, what's local, or domestic? Do I need to research V2ray docs for this? I left it as default.
    * TCP keep active packet delivery interval. I think it's usually called TCP keep alive interval. Is this related to the three Mux options above? It's hard to tell.
4. Can I have a nicer app logo? Red on yellow, wow, my eyes hurt from looking at it.

**Comment by nekohasekai** [comment]
1. This standard Android OS does not have permission to be "Autostart" or anything like that, as this is just a normal cross-application call through one of the four major components of Android.

For this I would recommend flashing to AOSP ROM, or buying an AOSP pre-installed or capable device.

I don't have those devices, so I can only offer some vague suggestions in the documentation, like granting all relevant permissions.

2. Maybe through F-Droid or Play Store (I'm submitting).

3. These are basically some of the proper names invented by v2ray-core

4. I don't have a better idea, maybe it needs a professional to make it.

**Comment by klzgrad** [comment]
> Autostart

I don't know, something like this https://gist.github.com/chandruark/3165a5ee3452f2b9ec7736cf1b4c5ea6.

Or at least, add a few words like "May need to turn on necessary permissions of this plugin app."

> proper names invented by v2ray-core

I haven't never used v2ray, so I make my guesses:

* Group: "Subscription groups"
* Security Advisory by Qv2ray: "Warn about insecure settings". At least should be security advices, because advisory means you have some vulnerabilities requiring updates.
* Apps VPN mode: should be "All", "Allow selected", "Disallow selected" https://developer.android.com/reference/android/net/VpnService.Builder#addAllowedApplication(java.lang.String)
* Domain resolution strategy AsIs, IPIfNonMatch, IPOnDemand: 
    * "How to resolve domains in routing rule matching":
        * "Never resolve",
        * "Resolve if no domain matches",
        * "Resolve on first IP rule"
* Enable traffic sniffing: Seems to be exactly what I guessed. In TPROXY or FakeDNS setup, the proxy receives a request with only an IP address. This makes domain based routing work poorly. To counter that it recovers domain names from HTTP request or TLS ClientHello. Now that SagerNet has no use of TPROXY and only FakeDNS, this option can be renamed as
    * "Recover domains from traffic for FakeDNS."
* DNS mode: This is your own creation that converts into routing config. You ought to explain it. Particularly local and domestic.
* TCP keep active packet delivery interval: This seems to be your own creation too. The code actually uses the correct name, TCP keep alive interval. The localization makes it worse. The issue with this setting is that its scope is not clear. From the code it seems this setting only applies to built in protocols, not plugins.

**Comment by Docop2** [comment]
It's a very great project !  Perhaps bit more details on the 'vpn' aspect.. and is dns related to ?

**Comment by klzgrad** [comment]
What is the resolution of these items? Like, I get it, "see v2fly docs for everything" could be an answer if this project aims to be a thin wrapper of v2fly, in which case the problem still remains that the scope is unclear as to which part is verbatim from v2fly upstream and which part is your own creation.

**Comment by kwaa** [comment]
> 4. Can I have a nicer app logo? Red on yellow, wow, my eyes hurt from looking at it.

I designed an app icon:
![example](https://user-images.githubusercontent.com/50108258/121818599-ba820a80-ccba-11eb-9125-12e0cda77f97.png)

use Amber#FFC107, "VPN Key" Icon (from Material Design) and pooh contour (but considering the DMCA, maybe what should be used to replace it)

**Comment by klzgrad** [comment]
So it seems it's not just me that would like a better looking logo. On this point it'd best if the official stance for making a new logo is made clear so to avoid wasting everyone's energy based on misunderstanding.
