### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by FarCry989** [SagerNet/SagerNet#107]
**Describe the bug**
1.Sometimes, Update button in "Group" after pressing is disappeared without reason! or doesn't show "No difference" or .....
 
2.Webdao is one of complete V2ray nodes in GitHub. V2rayNG can import this node but SagerNet doesn't! here's URL subscription:
https://raw.githubusercontent.com/webdao/v2ray/master/nodes.txt

**if it's not bug, please don't report this as spam please! (with regards)**

**Smartphone (please complete the following information):**
 - Device: S10 Samsung
 - OS: Android 10
 - Version 0.1-RC13

**Additional context**

**Comment by FarCry989** [comment]
#98

**Comment by ashaikh147** [comment]
@FarCry989 Do you have source code updated of v2rayNG? I will pay you nominal charges.
