### ISSUE TITLE
复制节点（导出一>导入）出错

### ISSUE THREAD

**Issue by ymcoming** [SagerNet/SagerNet#111]
**Describe the bug**
新建一个vless ws节点成功后，想添加另一同协议节点，于是导出到剪切板，再从剪切板导入。然而这操作完成后，新节点连接不上了（实际啥都没改，还是第一个节点，也连不上了）。

最后发现导出并导入后，Max early data自动变为2048 （原值为0），导致连接不上。手工改回0后可正常连接。

**To Reproduce**

**Logcat**
Export it yourself :)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**

**Comment by nekohasekai** [comment]
无法复现, 请提供示例链接.

**Comment by ymcoming** [comment]
ws的path原为/test，为了0-rtt,设为/test?ed=2048时可连接成功，导出再导入后，Max early data变为2048。可能这样重复了？但Max early data为2048，path为/test也连不上

**Comment by nekohasekai** [comment]
ed 即为 Xray 的 websocket max early data, 请确认服务器为 Xray 并导出日志给 https://t.me/SagerNetBot

**Comment by nekohasekai** [comment]
我看你是在 v2ray-core server 里设置了 xray 格式的?ed path (并没有用), 然后 SN 为了兼容 Xray 会自动打开 early data 所以无法连接.
