### ISSUE TITLE
The project generated some errors during the build process

### ISSUE THREAD

**Issue by wangshuohulala** [SagerNet/SagerNet#115]
I downloaded the project directly and unpacking the build produces the following error.
> Task :plugin:xtls:externalBuild FAILED
/Users/buding/SagerNet/run: line 5: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

Execution failed for task ':plugin:xtls:externalBuild'.
> Process 'command '/Users/buding/SagerNet/run'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I hope I can get an answer

**Comment by nekohasekai** [comment]
I think your bash is outdated

**Comment by nekohasekai** [comment]
Since SN includes many sub-modules, the source code downloaded directly cannot be compiled. Use git clone instead.

**Comment by wangshuohulala** [comment]
> 由于SN包含许多子模块，因此无法直接下载直接下载的源代码。使用git clone代替。

I still get an error using the command.
git clone --recurse-submodules https://github.com/SagerNet/SagerNet.git

**Comment by nekohasekai** [comment]
Try #82
