### ISSUE TITLE
希望能够添加对 ShadowsocksR-native 的支持

### ISSUE THREAD

**Issue by zyp997** [SagerNet/SagerNet#117]
项目地址：[https://github.com/ShadowsocksR-Live/shadowsocksr-native](https://github.com/ShadowsocksR-Live/shadowsocksr-native)
项目 Wiki 地址：[https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki)

**Comment by nekohasekai** [comment]
这个 wiki 似乎什么都没说，全是宣传，有一种 Xray 的风格 🤔

**Comment by zyp997** [comment]
SSRot 也是基于 WebSocket 协议

**Comment by nekohasekai** [comment]
他的文档看起来非常不靠谱，以及现在通过 TLS / WebSocket 的协议并不少，我的意思。
