### ISSUE TITLE
打开SagerNet时自动更新组/订阅

### ISSUE THREAD

**Issue by Kia678** [SagerNet/SagerNet#121]
Is your feature request related to a problem? Please describe.
由于本人使用的组/订阅经常有变动导致经常需要手动更新组/订阅，不太方便，希望可以增加：默认自动更新组/订阅功能（每次打开SagerNet时）

Describe the solution you'd like
打开SagerNet时自动更新组/订阅

Describe alternatives you've considered
暂无

Additional context
暂无

**Comment by GYQ-18** [comment]
可以像clash那样，做一个定时更新订阅的功能
