### ISSUE TITLE
Failed :: Unknown plugin naive-plugin

### ISSUE THREAD

**Issue by M33FT** [SagerNet/SagerNet#122]
Hi . .  
Thank you for your excellent App. I have never seen such a complete client.  This is really great.  The only problem I had and tested in rc13 to rc17 versions and it didn't work was NaiveProxy.
I have Naive that uses HTTPS protocol easily on PC and OpenWrt and it works but in SagerNet when running, it shows "Failed :: Unknown plugin naive-plugin" error.

What do you think the problem is?

![110171039-51b00a00-7e10-11eb-9d6a-35aaa0bba757](https://user-images.githubusercontent.com/63062740/120591959-3e81fa00-c452-11eb-9530-9c830dfbfc78.gif)

**Comment by nekohasekai** [comment]
The standard Android OS does not have permissions named "Autostart" or similar, as this is just a normal cross-application call through one of the four major components of Android, and the plugin does not run continuously in the background.

For this I would recommend flashing to AOSP ROM, or buying an AOSP pre-installed or compatible device.
