### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by FrzMtrsprt** [SagerNet/SagerNet#123]
**Is your feature request related to a problem? Please describe.**
Opening the app always blinds my eyes at night. Adding dark modes would make the app more eye-friendly.

**Describe the solution you'd like**
Add native dark modes to the app, with options `Light Mode`, `Dark Mode`, `Black Mode`, and `Follow System`.
Would be better if `Force Dark` is disabled throughout the app, with the parameter `setForceDarkAllowed()`.

**Describe alternatives you've considered**
Nope.

**Additional context**
The option `Follow System` should appear on all Android versions, instead of on Android 10 or later, as some Android distributions inplemented their own auto-switching dark modes.

**Comment by nekohasekai** [comment]
Contribution is welcome.
