### ISSUE TITLE
Garbage in port 6450 inbound definition with TCP DNS

### ISSUE THREAD

**Issue by klzgrad** [SagerNet/SagerNet#127]
Reproduce: Set DNS Settings:
* DNS Mode: Local
* Local DNS: tcp://8.8.8.8:53
* Enable domestic DNS: false

logcat actual:
```
"inbounds": [
  {
    "listen": "127.0.0.1",
    "port": 2080,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "userLevel": 8
    },
    "tag": "in"
  },
  {
    "listen": "127.0.0.1",
    "port": 6450,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "tcp://8.8.8.8:53",
      "network": "tcp,udp",
      "port": 53
    },
    "tag": "dns-in"
  }
],
```

logcat expected:
* `"address": "8.8.8.8",`
* `"network": "tcp"`? Is there some UDP to TCP translation in v2fly that could support `tcp,udp` both, or only tcp here?

**Comment by AkinoKaede** [comment]
Hmm, `network` is the protocol that `dokodemo-door` allowed.

**Comment by klzgrad** [comment]
Not a question, the `address` field can only contain "an IP address, like "1.2.3.4", or a domain name, like "v2ray.com"."

**Comment by nekohasekai** [comment]
> Not a question, the `address` field can only contain "an IP address, like "1.2.3.4", or a domain name, like "v2ray.com"."

https://github.com/SagerNet/SagerNet/issues/128#issuecomment-855520884

**Comment by klzgrad** [comment]
Verified.
