### ISSUE TITLE
Optimize TCP DNS setup

### ISSUE THREAD

**Issue by klzgrad** [SagerNet/SagerNet#129]
I try to have a setup for minimum latency DNS resolution. Alternatives: 1. FakeDNS creates much trouble in fixing its stale results. 2. DNS over HTTPS takes too much time, like several RTTs.

In principle the process goes like this: `[UDP *:53 -> tun2socks -> v2fly dns module -> TCP my_resolver:53] -> [Socks5 -> existing TLS tunnel] -> [Server -> TCP my_resolver:53]`. The first segment happens only locally. The majority of latency is in the second TLS segment. The last segment takes little time but still could also use a little caching to improve latency. With TCP DNS queries, the second segment will only take 1 RTT instead of 3 or more RTTs with HTTPS handshakes.

The above design does not work now.

First test:
* Routes: No routes; DNS Mode: Local, Local DNS: tcp://8.8.8.8:53, Enable domestic DNS: false
* Actual: The first segment connects directly to 8.8.8.8 without entering the second and third segment.

Second test:
* Routes: {ip:8.8.8.8 port:53 outbound:out}; DNS Mode: Local, Local DNS: tcp://8.8.8.8:53, Enable domestic DNS: false
* Actual: (Same as before) The first segment connects directly to 8.8.8.8 without entering the second and third segment.

<details>
  <summary>
logcat of the second test</summary>

```
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "tcp://8.8.8.8:53"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 2080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "tag": "in"
    },
    {
      "listen": "127.0.0.1",
      "port": 6450,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "tcp://8.8.8.8:53",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 2090
          }
        ]
      },
      "tag": "out"
    },
    {
      "protocol": "freedom",
      "tag": "bypass"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundDownlink": true,
      "statsOutboundUplink": true
    }
  },
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "outboundTag": "dns-out",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "bypass",
        "type": "field"
      },
      {
        "domain": [
          "example.com"
        ],
        "outboundTag": "bypass",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "network": "tcp",
        "outboundTag": "out",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```
</details>

Third test:
* Routes: ip:127.0.0.1 outbound:out; DNS Mode: Local, Local DNS: tcp://127.0.0.1:5353, Enable domestic DNS: false
* Actual: The TCP DNS query was proxied in the TLS tunnel.

I think the builtin route rule `{"outboundTag": "dns-out", "port": "53", "type": "field"}` has overridden the later rule of ip:8.8.8.8.

Desired changes:
1. DNS of tcp://my_resolver:53 is properly tunneled.
2. Create associated route rules for the TCP DNS setting without user intervention.

**Comment by AkinoKaede** [comment]
```
{
    "outboundTag": "dns-out",
    "port": "53",
    "type": "field"
}
```
This rule may route the DNS over TCP to `dns-out` outbound, and V2Ray will connect the destination without tunneling.

**Comment by arm64v8a** [comment]
> 2. DNS over HTTPS takes too much time, like several RTTs.


Actually it's very slow for me. It's not only a RTT problem.

```
2021/06/07 14:59:30 [Info] [1932474829] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2021/06/07 14:59:30 [Info] v2ray.com/core/app/dns: DOH//1.1.1.1 querying: www.google.com.
2021/06/07 14:59:30 [Info] v2ray.com/core/app/dispatcher: default route for tcp:1.1.1.1:443
2021/06/07 14:59:30 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:naive
2021/06/07 14:59:30 [Info] v2ray.com/core/app/dispatcher: default route for tcp:1.1.1.1:443
2021/06/07 14:59:30 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:naive
2021/06/07 14:59:30 [Info] v2ray.com/core/app/dns: DOH//1.1.1.1 got answer: www.google.com. TypeAAAA -> [xxxxxxxxxx] 114.514ms
2021/06/07 14:59:30 [Info] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canceled
2021/06/07 14:59:30 [Error] v2ray.com/core/app/dns: failed to retrieve response > Post "https://1.1.1.1/dns-query": io: read/write on closed pipe
2021/06/07 14:59:34 [Info] [1932474829] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2021/06/07 14:59:34 [Info] [1932474829] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:naive
```

It's a bug(?) of v2ray. I will talk to the v2ray developers.

When AAAA finished, v2ray **cancel** some context.

So the query of the A record fails, resulting a **5 seconds** waiting.

If I patch this, the delay of every DOH request is about 2-RTT

```
diff --git a/app/dns/nameserver_doh.go b/app/dns/nameserver_doh.go
@@ -239,8 +237,7 @@ func (s *DoHNameServer) sendQuery(ctx context.Context, domain string, clientIP n
                        dnsCtx = session.ContextWithMuxPrefered(dnsCtx, true)
 
                        var cancel context.CancelFunc
-                       dnsCtx, cancel = context.WithDeadline(dnsCtx, deadline)
-                       defer cancel()
+                       dnsCtx, _ = context.WithDeadline(dnsCtx, deadline)
 
                        b, err := dns.PackMessage(r.msg)
                        if err != nil {
```

I don't know why no keep-alive.

**Comment by rurirei** [comment]
> and V2Ray will connect the destination without tunneling.

@AkinoKaede what is **tunneling** you said?

outbound_dns will do a dns forwarding.

**Comment by rurirei** [comment]
@klzgrad this may a correct process:
[UDP *:53 -> tun2socks -> v2fly dns module (dns outbound && dns module) -> TCP my_resolver:53] -> [v2fly routing (you could do routing with dns_module_tag) -> existing TLS tunnel] -> [Server -> TCP my_resolver:53]

```jsonc
// routing to dns_module -> do dns forwarding
{
    "outboundTag": "dns-out",
    "port": "53",
    "type": "field"
}

{
    "outboundTag": "proxy",
    "inboundTag": "nameserver",
    "type": "field"
}

// dns_module
{
    "servers": ["tcp://8.8.8.8"],
    "tag": "nameserver"
}
```

**Comment by AkinoKaede** [comment]
> > and V2Ray will connect the destination without tunneling.
> 
> @AkinoKaede what is **tunneling** you said?
> 
> outbound_dns will do a dns forwarding.

Sorry for my poor English. The dns outbound will direct connect the destination if the connection from DNS app.

**Comment by rurirei** [comment]
@AkinoKaede no, it's for dns request expect IP query.

**Comment by AkinoKaede** [comment]
@rurirei 

> @AkinoKaede no, it's for dns request except IP query.

hmm

*又顺带提一句，虽然这种情况不常发生，但是万一万一你不小心把内置 DNS 服务器发出的流量，指向了 DNS 出站协议。这时候按理说 DNS 出站代理会再一次把查询扔回给 DNS 服务器，造成死循环。这种情况我们已经考虑到了，DNS 出站协议能够识别出来自内置 DNS 服务器的流量，不会把它们扔回去，而且直接发出去。*
-- From [Steemit](https://steemit.com/cn/@v2ray/dns)

**Comment by rurirei** [comment]
@arm64v8a could you upload the complete logs of a DoH request?

**Comment by arm64v8a** [comment]
> @arm64v8a could you upload the complete logs of a DoH request?

That's all.

I think it's off-topic here. Let's talk about the DoH bug at https://github.com/v2fly/v2ray-core/pull/1057
