### ISSUE TITLE
Brook - fail tell unknow plugin

### ISSUE THREAD

**Issue by Docop2** [SagerNet/SagerNet#132]
Hi
 So on android10, i intall your latest ver. app and it's very very great as it gather all. But for the brook, when i start a working server (that i can reach from all other place..) i got message : Failed : unknow brook plugin.

protocol is set as:  wss , port is set.  in the address if i put just the domain name or wss://domain.com  or wss://domain.com:443  or even just the ip = i always get the failed message.

 App do connect fine to a http proxy or to a shadowsock server.  Just the Brook section that don't work.

Thanks

**Comment by Docop2** [comment]
Also, i did have install the brook app .apk , witch can do connect fine to the wss. So is there an extra plugin to put or it's currently missing in the release ?

**Comment by nekohasekai** [comment]
RTFM
