### ISSUE TITLE
Spotify不能被代理

### ISSUE THREAD

**Issue by riverscn** [SagerNet/SagerNet#133]
**Describe the bug**
尝试了各种设置方式，Spotify都不能被代理，显示离线。

**To Reproduce**
1. 打开sagernet
2. 打开Spotify

**Logcat**
`SagerNet 0.1-rc21 (76) on API 30
ABI arm64-v8a (arm64-v8a, armeabi-v7a, armeabi)
--------- beginning of system
06-12 11:47:58.843 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=801.7423, y[0]=1264.527, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566816160, downTime=566816160, deviceId=2, source=0x1002, displayId=0 }
06-12 11:48:09.130 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=410.0, y[0]=1734.0, toolType[0]=TOOL_TYPE_UNKNOWN, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566826447, downTime=566826447, deviceId=0, source=0x10001002, displayId=0 }
06-12 11:48:09.420 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=410.0, y[0]=1877.0, toolType[0]=TOOL_TYPE_UNKNOWN, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566826736, downTime=566826736, deviceId=0, source=0x10001002, displayId=0 }
06-12 11:48:09.821 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=410.0, y[0]=1877.0, toolType[0]=TOOL_TYPE_UNKNOWN, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566827138, downTime=566827138, deviceId=0, source=0x10001002, displayId=0 }
06-12 11:48:10.195 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=410.0, y[0]=1877.0, toolType[0]=TOOL_TYPE_UNKNOWN, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566827512, downTime=566827512, deviceId=0, source=0x10001002, displayId=0 }
06-12 11:48:10.578 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=410.0, y[0]=1877.0, toolType[0]=TOOL_TYPE_UNKNOWN, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566827893, downTime=566827893, deviceId=0, source=0x10001002, displayId=0 }
06-12 11:48:10.959 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=410.0, y[0]=2117.0, toolType[0]=TOOL_TYPE_UNKNOWN, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566828275, downTime=566828275, deviceId=0, source=0x10001002, displayId=0 }
06-12 11:48:38.960 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=821.76086, y[0]=1315.5482, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566856277, downTime=566856277, deviceId=2, source=0x1002, displayId=0 }
06-12 11:48:39.685 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=782.72473, y[0]=1526.6361, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566857002, downTime=566857002, deviceId=2, source=0x1002, displayId=0 }
06-12 11:48:41.046 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=734.68024, y[0]=1791.7466, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566858362, downTime=566858362, deviceId=2, source=0x1002, displayId=0 }
06-12 11:48:41.548 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=759.70337, y[0]=1837.7657, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566858865, downTime=566858865, deviceId=2, source=0x1002, displayId=0 }
06-12 11:48:42.175 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=989.91656, y[0]=1076.4486, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566859492, downTime=566859492, deviceId=2, source=0x1002, displayId=0 }
06-12 11:48:42.251 30379 30379 D OplusViewRootUtil: initSwipState, isDisplayCompatApp false
06-12 11:48:42.251 30379 30379 D OplusViewRootUtil: mScreenHeight 2400, mScreenWidth 1080
06-12 11:48:42.275 30379 30379 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.DecorView@973e717[AppManagerActivity]
06-12 11:48:43.676 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=157.1455, y[0]=183.0763, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566860993, downTime=566860993, deviceId=2, source=0x1002, displayId=0 }
06-12 11:48:44.766 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=941.8721, y[0]=2049.8542, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566862081, downTime=566862081, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:28.106 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=97.08989, y[0]=198.08253, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x1, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566965424, downTime=566965424, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:29.529 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=573.531, y[0]=928.38684, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566966843, downTime=566966843, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:33.939 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=708.6561, y[0]=1447.6033, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566971256, downTime=566971256, deviceId=2, source=0x1002, displayId=0 }
--------- beginning of main
06-12 11:50:34.005 30379 30379 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=708.6561, y[0]=1447.6033, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566971321, downTime=566971256, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:34.006 30379 30379 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=708.6561, y[0]=1447.6033, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566971321, downTime=566971256, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:34.011 30379 30379 E Parcel  : Reading a NULL string not supported here.
06-12 11:50:34.054 30379 30379 D OplusGameShakeOptimizationHelper: onWindowFocusChanged pkgName = io.nekohasekai.sagernet mGameShakeConfig = null
06-12 11:50:34.055 30379 30379 D OplusGameShakeOptimizationHelper: getGameShakeConfig = null
06-12 11:50:35.708 30379 30379 D OplusGameShakeOptimizationHelper: onWindowFocusChanged pkgName = io.nekohasekai.sagernet mGameShakeConfig = null
06-12 11:50:35.709 30379 30379 D OplusGameShakeOptimizationHelper: getGameShakeConfig = null
06-12 11:50:39.096 30379 30379 D ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=751.696, y[0]=1278.5327, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566976413, downTime=566976413, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:39.096 30379 30379 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=751.696, y[0]=1278.5327, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566976413, downTime=566976413, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:39.096 30379 30379 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=751.696, y[0]=1278.5327, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566976413, downTime=566976413, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:39.161 30379 30379 D ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=751.696, y[0]=1278.5327, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566976478, downTime=566976413, deviceId=2, source=0x1002, displayId=0 }
06-12 11:50:39.162 30379 30379 D ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=751.696, y[0]=1278.5327, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=566976478, downTime=566976413, deviceId=2, source=0x1002, displayId=0 }

`

**Expected behavior**
Spotify被代理

**Screenshots**
![Screenshot_2021-06-10-09-58-53-10_0438eb925998df20b3482ec25499d226.jpg](https://user-images.githubusercontent.com/555062/121452721-7cdb6400-c9d2-11eb-932b-c916d36a0f8f.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 9 国行
 - OS: Android 11
 - Version Color OS 11.2
 
**Additional context**
设置截图
![Screenshot_2021-06-12-11-48-27-01.jpg](https://user-images.githubusercontent.com/555062/121764150-3f164100-cb74-11eb-994a-418e2c058735.jpg)

**Comment by nekohasekai** [comment]
无法复现 请提供更多信息

**Comment by riverscn** [comment]
补充了关于系统版本的更多信息和设置截图

**Comment by nekohasekai** [comment]
是最新版吗。

**Comment by riverscn** [comment]
补充了log

**Comment by riverscn** [comment]
> 是最新版吗。

是

**Comment by nekohasekai** [comment]
到开发者设置调大日志缓冲区，重启，打开代理和 spotify 复现，重新发日志。注意移除敏感信息，直接发文件。

**Comment by riverscn** [comment]
手机系统升级以后好了……
