### ISSUE TITLE
is there are reason for integrating older SS-libev library?

### ISSUE THREAD

**Issue by mfc** [SagerNet/SagerNet#137]
hi devs, 
i really appreciate your efforts on this project. i was curious why you chose to use https://github.com/shadowsocksRb/shadowsocksr-libev rather than https://github.com/shadowsocks/shadowsocks-libev which is kept up-to-date with security/bug fixes?

thanks!

**Comment by nekohasekai** [comment]
This is an old Shadowsocks fork called ShadowsockSR and is still widely used in China.

**Comment by mfc** [comment]
okay, but does that make it less likely to work / be reliable? i see here the recommendation to avoid active probing and disconnections is to use up-to-date `shadowsocks-libev`:  
* https://gfw.report/blog/ss_advise/zh/
* https://gfw.report/blog/ss_tutorial/zh/

or that only important server-side?

**Comment by nekohasekai** [comment]
![Image](https://user-images.githubusercontent.com/56506714/121672780-c61ad900-cae2-11eb-8756-ff54c9809125.png)

**Comment by mfc** [comment]
okay, thank you for your time! i think i understand, it is included for compatibility purposes. and `shadowsocks-libev` should also work fine.
