### ISSUE TITLE
Question about the different apps named "SagerNet"on F-Droid?

### ISSUE THREAD

**Issue by sudomain** [SagerNet/SagerNet#153]
Hello,

I want to try using this app but I'm not sure which one I need. There are 6 named "SagerNet" that have been updated in the last month and all of them link to this repo under the `Source Code` section of F-Droid.

EDIT: sorry for not actually asking a question: What are the differences between the 6 apps named "SagerNet"?

**Comment by nekohasekai** [comment]
This is a bug in the F-Droid client, and it displays normally on the web page. By the way, you can distinguish them by icons.
