### ISSUE TITLE
使用 V2Ray 自定义配置时，若 outbound 字段末尾 protocol 键之后没有其它键，配置无法正常解析

### ISSUE THREAD

**Issue by EAimTY** [SagerNet/SagerNet#155]
**Describe the bug**

使用 V2Ray 自定义配置时，若 outbound 字段末尾 protocol 键之后没有其它键，配置无法正常解析，报 `java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.nekohasekai.sagernet.fmt.v2ray.V2RayConfig$OutboundObject.protocol' on a null object reference`

**To Reproduce**

建立一个自定义配置，配置类型为 V2Ray，内容如下：

    {
        "outbounds": [
            {
                "settings": {
                    "servers": [
                        {
                            // ...
                        }
                    ]
                },
                "streamSettings": {
                    // ...
                },
                "protocol": "socks"
            }
        ]
    }

配置将无法启动，报 `java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.nekohasekai.sagernet.fmt.v2ray.V2RayConfig$OutboundObject.protocol' on a null object reference`

只有当 `"protocol": "socks"` 后有如 `"tag": "outBound_PROXY"` 等其它键时，配置才能正常启动。同样的配置文件，在 V2RayNG 下可以正常使用。

**Logcat**

    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.nekohasekai.sagernet.fmt.v2ray.V2RayConfig$OutboundObject.protocol' on a null object reference
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.fmt.v2ray.V2RayConfig$LazyOutboundConfigurationObject.getType(Unknown Source:2)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.fmt.gson.-$$Lambda$JsonLazyInterface$OY_Ww2ia3v1msn_tec5Y6jNdhGQ.invoke(Unknown Source:1)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.fmt.gson.JsonLazyAdapter.write(Unknown Source:10)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.fmt.gson.JsonLazyAdapter.write(Unknown Source:2)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(Unknown Source:4)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(Unknown Source:5)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at com.google.gson.Gson.toJson(Unknown Source:37)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at com.google.gson.Gson.toJson(Unknown Source:7)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildCustomConfig(Unknown Source:9)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.bg.ProxyInstance.init(Unknown Source:512)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(Unknown Source:55)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:2)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:86)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at android.os.Handler.handleCallback(Handler.java:938)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at android.os.Handler.dispatchMessage(Handler.java:99)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at android.os.Looper.loop(Looper.java:223)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at java.lang.reflect.Method.invoke(Native Method)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    06-28 22:30:05.573  6231  6231 W BaseService$Interface$onStartCommand$2: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Expected behavior**

配置应正常启动

**Smartphone (please complete the following information):**

 - Device: Pixel 4
 - OS: Android 11
 - Version: RQ3A.210605.005

**Comment by nekohasekai** [comment]
应已被修复
