### ISSUE TITLE
Add switch button into system quick setting panel

### ISSUE THREAD

**Issue by Discreater** [SagerNet/SagerNet#156]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Like this
![image](https://user-images.githubusercontent.com/41231596/123824023-44270e80-d930-11eb-946a-b52eff25ef24.png)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by nekohasekai** [comment]
Already exists.
