### ISSUE TITLE
启动VPN连接困难

### ISSUE THREAD

**Issue by Geek-Joe** [SagerNet/SagerNet#165]
**Describe the bug**

1. 使用的是自己编写的配置（Custom Config）
2. 点击右下角的FAB启动VPN连接后很快自己又会断开（钥匙图表消失），反复操作数次后能连稳，稳定下来后没有别的问题。
3. 同样的配置文件在PC端无问题

**Logcat**
SagerNet 0.2-rc01 (280) on API 24
ABI arm64-v8a (arm64-v8a, armeabi-v7a, armeabi)
--------- beginning of main
07-05 10:08:44.817 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:44.817 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:45.715 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:45.715 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:45.756 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:45.756 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:46.506 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:46.506 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:47.507 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:47.508 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:47.544 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:08:47.544 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:02.028 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:02.045 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:02.062 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:02.079 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:02.095 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:04.475 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:04.475 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:05.747 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:05.747 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:07.600 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:07.600 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:07.729 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:07.729 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:07.921 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:07.922 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:08.059 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:09:08.059 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:07.737 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:07.737 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:08.341 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:08.341 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:09.193 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:09.193 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:09.234 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:09.234 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:21.756 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:21.756 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:22.017 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:22.017 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:38.580 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:38.580 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:38.748 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:38.749 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:38.920 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:38.920 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:39.092 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:39.092 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:39.252 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:39.252 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:39.692 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:39.692 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:40.130 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:40.130 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:40.693 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:40.693 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:41.611 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:41.611 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:42.631 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:42.631 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:42.802 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:42.802 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:43.037 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:43.037 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:43.588 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:43.588 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:44.452 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:44.452 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:44.487 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:44.487 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:47.324 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:47.324 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:50.598 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:50.598 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:50.767 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:50.767 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:51.282 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:51.282 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:51.691 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:51.691 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:55.857 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:55.857 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:55.886 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:15:55.886 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:03.648 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:03.648 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:04.404 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:04.404 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:04.438 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:04.438 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:21.061 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:21.078 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:21.095 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:21.112 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:21.129 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:23.188 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:40.991 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:40.991 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:42.613 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:42.614 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:42.651 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:42.651 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:45.555 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:45.556 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:47.102 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:47.102 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:47.359 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:47.359 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:47.551 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:47.551 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.012 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.012 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.354 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.354 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.523 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.523 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.717 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.717 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.908 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:48.908 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:49.100 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:49.100 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:49.295 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:49.295 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:49.487 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:49.487 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:50.058 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:50.058 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:50.716 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:50.716 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:50.757 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:16:50.757 30426 30426 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-05 10:18:23.377  3078  6620 E art     : ashmem_create_region failed for 'indirect ref table': Too many open files
07-05 10:18:23.377  3078  6620 F go/Seq  : failed to attach current thread
07-05 10:18:23.384  3078  6622 E art     : ashmem_create_region failed for 'indirect ref table': Too many open files
07-05 10:18:23.384  3078  6622 F go/Seq  : failed to attach current thread
--------- beginning of crash
07-05 10:18:23.389  3078  6622 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 6622 (kai.sagernet:bg)
07-05 10:18:23.390  3078  6620 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 6620 (kai.sagernet:bg)
07-05 10:18:41.792  6586  6586 E tun2socks: ERROR(BConnection): recv failed
07-05 10:19:08.120  6991  7559 E art     : ashmem_create_region failed for 'indirect ref table': Too many open files
07-05 10:19:08.120  6991  7559 F go/Seq  : failed to attach current thread
07-05 10:19:08.280 30426  1975 E NativeCrypto: Unknown error 5 during handshake

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [ZTE Blade A3]
 - OS: [Android7.0]
 - Version [0.2-rc01]

**Additional context**
我的配置文件：
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "none"
  },
  "dns": {
    "servers": [
      "https://firefox.dns.nextdns.io/",
      "45.90.28.24",
      "45.90.30.24"
    ],
    "queryStrategy": "UseIPv4",
    "clientIp": "111.172.7.243",
    "tag": "dns_inbound"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "tag": "socks-inbound",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    },
    {
      "port": 8080,
      "listen": "127.0.0.1",
      "tag": "http-inbound",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct",
      "settings": {
        "domainStrategy": "UseIPv4"
      }
    },
    {
      "protocol": "vmess",
      "tag": "sg-proxy",
      "settings": {
        "vnext": [
          {
            "address": "v2sg2-ws-tls.yuntiss.pro",
            "port": 48302,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 0
              }
            ]
          },
          {
            "address": "v2sg3-ws-tls.yuntiss.pro",
            "port": 48302,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "protocol": "vmess",
      "tag": "kr-proxy",
      "settings": {
        "vnext": [
          {
            "address": "v2kr2-ws-tls.yuntiss.pro",
            "port": 48502,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "protocol": "vmess",
      "tag": "jp-proxy",
      "settings": {
        "vnext": [
          {
            "address": "v2jp-ws-tls.yuntiss.pro",
            "port": 48104,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 1
              }
            ]
          },
          {
            "address": "v2jp3-ws-tls.yuntiss.pro",
            "port": 48104,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 1
              }
            ]
          },
          {
            "address": "v2jp4.yuntiss.pro",
            "port": 48104,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "protocol": "vmess",
      "tag": "hk-proxy",
      "settings": {
        "vnext": [
          {
            "address": "v2hk4-ws-tls.yuntiss.pro",
            "port": 48204,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 1
              }
            ]
          },
          {
            "address": "v2hk6-ws-tls.yuntiss.pro",
            "port": 48204,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "protocol": "vmess",
      "tag": "tw-proxy",
      "settings": {
        "vnext": [
          {
            "address": "v2tw-ws-tls.yuntiss.pro",
            "port": 48404,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 1
              }
            ]
          },
          {
            "address": "v2tw-2.yuntiss.pro",
            "port": 48404,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "protocol": "vmess",
      "tag": "uk-proxy",
      "settings": {
        "vnext": [
          {
            "address": "v2uk.yuntiss.pro",
            "port": 48702,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "protocol": "vmess",
      "tag": "de-proxy",
      "settings": {
        "vnext": [
          {
            "address": "v2de.yuntiss.pro",
            "port": 48802,
            "users": [
              {
                "id": "XXXXX",
                "alterId": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "protocol": "blackhole",
      "tag": "blocked"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": [
      {
        "type": "field",
        "port": "53",
        "inboundTag": [
          "dns-inbound"
        ],
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domains": [
          "geosite:category-ads",
          "geosite:category-porn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": [
          "0.0.0.0",
          "[::]"
        ]
      },
      {
        "type": "field",
        "domains": [
          "domain:dns.nextdns.io"
        ],
        "balancerTag": "balancer"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:!cn"
        ],
        "balancerTag": "balancer"
      }
    ],
    "balancers": [
      {
        "tag": "balancer",
        "selector": [
          "sg",
          "kr",
          "jp",
          "hk",
          "tw",
          "uk",
          "de"
        ],
        "strategy": {
          "type": "leastPing"
        }
      }
    ]
  },
  "transport": {
    "tcpSettings": {
      "header": {
        "type": "none"
      }
    },
    "wsSettings": {
      "path": "/cpyhyfd3"
    }
  },
  "observatory": {
    "subjectSelector": [
      "sg",
      "kr",
      "jp",
      "hk",
      "tw",
      "uk",
      "de"
    ]
  }
}

**Comment by nekohasekai** [comment]
已经修复的问题，请等下个版本发布。退出原因是配置错误，目测是因为 /var/log 在 android 不存在。

**Comment by nekohasekai** [comment]
Should be fixed.
