### ISSUE TITLE
导入文件的方式, 导入自定义配置

### ISSUE THREAD

**Issue by rogerBridge** [SagerNet/SagerNet#168]
**Is your feature request related to a problem? Please describe.**
在我分享配置给我的朋友们的时候, 我发现: 通过分享文件的形式, 导入的自定义配置, app会裁剪一部分, 如果通过剪贴板的话, 存在被其他应用读取配置详情的风险, 通过sn://xx的方式的话, sn协议我不明白是否公开, 如果不是公开的话, 那我的这个issue没有意义, 请关闭, 如果是公开的话, 风险同上

**Describe the solution you'd like**
通过导入文件的形式, 导入自定义配置

**Describe alternatives you've considered**

**Additional context**

**Comment by rogerBridge** [comment]
可以通过导出sn://config:的形式, 复制到一个文本文件中, 然后导入文本文件, 即可导入自定义配置

**Comment by rogerBridge** [comment]
更新问题描述:
情景: 两个人, a和b, a通过分享自定义配置文件的方式向b分享自己的配置, 发现: b导入配置文件的时候会出现裁剪的情况(app只会读取一些特定的键值对), 导致b导入的配置信息不完全;
期望加入的特性: 通过导入文件的方式, 导入自定义配置(现有的导入文件的方式会被app裁剪)
已发现的方法: a导出自定义配置文件的: sn://config... 形式, 保存在配置文件中, 将这个配置文件config.sn发给b, b可以通过导入文件config.sn, 来导入a的自定义配置.

**Comment by lsjiaowo** [comment]
楼主，我测试了下，我在我的配置的第一行加上了sn://config（我用的协议是naiveproxy，所以我改成sn://naive）
导入之后，只是生成一个新的配置，里面内容是空的，等于没导入。
不知道具体怎样填写才能完整的导入自定义的配置内容，能看下你的配置模板吗？
