### ISSUE TITLE
使用了中转的代理需要开启关闭证书检查才能连接

### ISSUE THREAD

**Issue by sunnyhu2003** [SagerNet/SagerNet#179]
Vmess+nginx+ws+tls代理经过中转后，服务器填入另外一个域名，端口也更改（不过这不是重点），连接后无网络。开启关闭证书检查后有网络。
原代理证书配置正确，不需要关闭证书检查网络也正常。

是用了服务器的域名而不是ws主机来校验？？

 - Device: Redmi K30 Ultra
 - OS:  Android11
 - Version 0.2 RC06

**Comment by nekohasekai** [comment]
没有填写 SNI
