### ISSUE TITLE
即使开启域名重写，play商店依然无法正常下载

### ISSUE THREAD

**Issue by aria001** [SagerNet/SagerNet#214]
### 知情同意表

本知情同意表格适用于希望提交错误报告的用户。本表格意在确保您知晓并理解以下内容：提交报告的的风险、收益、其他可选选项、用户义务、以及您应注意的事项;

您应该已经了解到提交报告并非解决错误的唯一方式, 就像染色体和性器官并不能定义您的性别身份一样, 提交报告并不是问题是否能够被解决的决定性因素;

您应该首先尝试学习文档, 了解一些操作系统与网络通信的基本常识, 并与其他用户充分讨论, 以确保这是 SagerNet 而不是您的设置或其他程序 (如 v2ray-core) 的错误;

我们建议您首先花足够的时间通过提问, 阅读, 研究等方式了解 SagerNet, 并考虑使用本软件可能对您和您生活产生的影响.

若您有任何关于本同意书的问题, 或在应用使用期间产生任何问题, 请向用户群组提出问题而不是滥用 issues 区, 您也可以随时选择停止使用 SagerNet —— 不用通知我们.

---

> 请于下方括号中填写 y 以确认.

(y) 本人 ___(填写名称或网名)___ 为 SagerNet **最新版本** 之用户，并希望提交错误报告.

(y) 我理解 Project S 作者为业余开发者, 对计算机科学与网络通信的研究尚不充分, 没有任何专业支持为我提供. 如果可能, 我将自己解决问题并提交拉取请求.

(y) 我理解 SagerNet 为自由软件且没有非自由依赖, 我有发布、研究、修改和改进软件的自由, 但不得将修改版本作为专有软件发布 (包括不发布或更新源代码、混淆源代码、引入专有依赖).

(y) 我理解 SagerNet 为免费发行之软件, 除非另有书面说明, 全部的风险, 如绕过网络审查产生的以下法律的风险, 且其中一些可能造成财产损失甚至生命危险 (均有真实事件), 都由您来承担:

* 教育训诫
* 依法控制
* 拘留
* 免职
* 传唤警告
* 执行指定居所监视居住
* 警告处罚
* 拘役
* 有期徒刑
* 不公开审理

---

### 描述问题

如标题所描述，域名重写似乎并未按照期望的效果，使play商店正常下载
日志显示，所有*.googleapis.cn被直接覆写成了googleapis.com似乎是导致无法下载的原因
尝试只将services.googleapis.cn重写为services.googleapis.com，能够下载软件，因此我建议将域名重写的默认值按此设置
### 如何复现

1 域名重写设置保持默认
2 在play商店随便下载一款软件，没有产生任何下载速度
3 单独添加对domain:googleapis.cn的代理规则，能正常下载

### 调试信息

> 关于 -> 导出调试信息

**如果您不直接发送文件, 请使用 Markdown code 块格式, 否则您的 issue 将被直接关闭!**

```
复现前请确保您已开启 "启用日志" 设置.

如果您的日志文件过小, 请到开发者设置增大日志缓冲区并重启设备以复现并重新发送日志.
```
```
08-08 01:03:56.056  3716  8279 I GoLog   : [Info] [913254887] proxy/freedom: failed to get IP address for domain services.googleapis.cn > empty response
08-08 01:03:56.056  3716  8279 I GoLog   : [Info] [913254887] transport/internet/tcp: dialing TCP to tcp:services.googleapis.cn:443
08-08 01:03:56.056  3716  8279 I GoLog   : [Debug] app/dns: found replaced domain: services.googleapis.cn -> googleapis.com. Try to unwrap it
08-08 01:03:56.056  3716  8279 I GoLog   : [Info] app/dns: domain replaced: services.googleapis.cn -> googleapis.com
08-08 01:03:56.056  3716  8279 I GoLog   : [Debug] app/dns: domain googleapis.com will use DNS in order: [FakeDNS DOH//1.0.0.1]
08-08 01:03:56.056  3716  8279 I GoLog   : [Debug] app/dns: found replaced domain: services.googleapis.cn -> googleapis.com. Try to unwrap it
08-08 01:03:56.056  3716  8279 I GoLog   : [Info] app/dns: domain replaced: services.googleapis.cn -> googleapis.com
08-08 01:03:56.056  3716  8279 I GoLog   : [Debug] app/dns: domain googleapis.com will use DNS in order: [FakeDNS DOH//1.0.0.1]
08-08 01:03:56.056  3716  8279 I GoLog   : [Info] app/dns: FakeDNS got answer: googleapis.com -> [198.18.0.2]
08-08 01:03:56.057  3716  8278 I GoLog   : [Info] app/dns: FakeDNS got answer: googleapis.com -> [198.18.0.2]
08-08 01:03:56.118  3716 31015 D DirectUdpForwarder: Accepted udp connection from com.google.android.gms, com.google.android.gsf (10156): 172.19.0.1:50853 ==> 172.19.0.2:53
```

### 屏幕截图

如果适用, 请添加屏幕截图以帮助解释您的问题.

### 设备信息

- 内核版本: [例. 4.19.114]
- 设备型号: [例. MI6]
- 操作系统: [例. MIUI10 Android8.1]

### 附加上下文

在此处添加有关该问题的任何其他上下文.

**Comment by listenerri** [comment]
在路由配置中增加 google 所有域名走代理，就能正常下载了
如果有设置绕过中国的相关路由规则，记得**长按并拖动**新增的 google 走代理规则条目，将其拖动到第一位，否则不生效

**Comment by IAMIBM** [comment]
Useful
