### ISSUE TITLE
The version 0.3-rc14 stop working 

### ISSUE THREAD

**Issue by Apanj** [SagerNet/SagerNet#219]
The new version 0.3-rc14 stop working as soon as start on Android 6.0 LG -G4 Arm 64 v8a .

**Comment by one5tep** [comment]
I also found this problem

**Comment by AkinoKaede** [comment]
Please send your logs.

**Comment by one5tep** [comment]
> Please send your logs.

can't open app

**Comment by Apanj** [comment]
I also can not open app !
