### ISSUE TITLE
[Feature request] 可更换内置分流数据

### ISSUE THREAD

**Issue by CalmLong** [SagerNet/SagerNet#22]
**Is your feature request related to a problem? Please describe.**
想一直开程序，但是内置用于分流的数据比较少，流量容易走代理。

**Describe the solution you'd like**
希望可以更换 GeoIP 和 GeoSite 的数据，本地导入或者在线导入都可以。

若 SagerNet 不兼容 V2Ray 的 geo 数据格式，也希望可以自定义

**Describe alternatives you've considered**
在设置中只代理部分程序，但是这样去广告的效果就被折扣了

**Additional context**
![image](https://user-images.githubusercontent.com/37164399/116642065-997e8800-a9a0-11eb-8390-7dc11d78645d.png)

**Comment by nekohasekai** [comment]
因为设计的自定义路由比较复杂，所以放在后面实现了。

自定义 GeoIP 和 GeoSite 是支持的，但由于前一条原因，还没有写更新界面，可以手动放置到 内部存储/Android/data/io.nekohasekai.sagernet/files 文件夹下替换 (需要自行创建文件夹)

**Comment by CalmLong** [comment]
发现点问题

自定义 GeoSite 确实会生效，但是有部分域名已经加入到 cn 标签里面，但是还会走代理

用的手机是 荣耀V30PRO/Android10/MagicUI4.0/EMUI11 

这些域名是收集系统程序(主题、天气等)所访问的域名
```
full:oauth-login-drcn.platform.dbankcloud.com
full:openlocation-drcn.platform.dbankcloud.com
full:grs.dbankcloud.com
full:service-cn.hwccpc.com
```
用 Clash for Android 测试不会出现
用 V2Ray core Windows 直接用浏览器访问也不会复现

猜测会不会是 VPN Service 的问题

这是路由配置截图

![image](https://user-images.githubusercontent.com/37164399/116665556-81bcf900-a9cc-11eb-9a25-a85b6998f2d7.png)

**Comment by Kookemoon** [comment]
Ability to add "Front Proxy" that supports Socks5 & HTTP(s) proxies like this open-source app:
https://github.com/xxf098/shadowsocksr-v2ray-trojan-android


Ability  to add geoip:ir for bypassing IR region. & ability to import or enter "Custom rules" like v2rayNG (Direct IPs or Domains).

**Comment by Kookemoon** [comment]
![Uploading Screenshot_20210501-135935_SSRRAY.jpg…]()

**Comment by nekohasekai** [comment]
抱歉，搞错目录了，下个版本之前都还在 data 的 files 里 (

**Comment by SekiBetu** [comment]
@CalmLong 建议 reopen 这个 issue, close 了容易忘
