### ISSUE TITLE
Request to add new encryption

### ISSUE THREAD

**Issue by Amirufc** [SagerNet/SagerNet#224]
Hi,
Please add chacha20 cryptography related to the [V2rayNG](https://github.com/2dust/v2rayNG) project to SagerNet, this cryptography is very necessary and useful for existing ShadowSocks in [bVPN](https://www.bvpn.com/) and,... that do not work in SagerNet.

**Comment by NudePlease** [comment]
**Chacha20** is Stream Cipher. Stream ciphers are completely broken and will be removed soon. New users must use AEAD ciphers.
