### ISSUE TITLE
列表内服务器超过一定数目后负载均衡不能连接

### ISSUE THREAD

**Issue by standritsu** [SagerNet/SagerNet#238]
机场更新后列表有62个配置，更新前忘了看，新增了大约10个

负载均衡策略选ping，类型选分组，按连接后显示vpn已经建立，但无法测试延迟，也无法连通，可用内存一直减少直到耗尽

如果把负载均衡类型改为列表，单独把列表里面的一些（不是全部）服务器添加进去，一切正常

另一个只有22个配置的机场列表完全没有问题

系统是MIUI 12.5 内测版21.8.25 android 11

**Comment by nekohasekai** [comment]
v2ray-core 问题。
