### ISSUE TITLE
关于更新订阅（组）的问题

### ISSUE THREAD

**Issue by hc050817** [SagerNet/SagerNet#240]
最近遇到一个问题，就是更新订阅会显示Connection refused （软件不连接代理时会出现，如果连接可用代理则能成功更新订阅）
设备型号：红米note10pro
Sagernet版本：0.3-RC07(后面我更新到了最新版的0.5-rc02还是这样）
是不是说更新订阅必须要软件开启代理才行呢？大佬请解答一下

**Comment by nekohasekai** [comment]
Connection refused 意思是你订阅地址被墙了，不连接代理怎么更新呢？
