### ISSUE TITLE
Wireguard plugin is unavailable

### ISSUE THREAD

**Issue by dennis90a** [SagerNet/SagerNet#249]
### Describe the bug
The wireguard plugin isn't available from the play store or github releases.
### To Reproduce

1. Add a wireguard config/use the warp generator
2. Try connecting
3. App asks you to download the wireguard plugin, shows 2 options - play store and download
4. First option - Play store says app not found, Second option - sagernet website shows link pointing to github releases for wireguard plugin, but there is no wireguard plugin under github releases

### Screenshots

![Screenshot_20210909-111940_Vivaldi](https://user-images.githubusercontent.com/90372818/132630286-e01a5e0a-6f57-4964-8e4c-952bc5f6238f.png)

### Expected behavior

Expected wireguard plugin to be found on play store/github releases

### Smartphone (please complete the following information)

- Kernel version: -
- Device: Mi 11x
- OS: Android 11

**Comment by dennis90a** [comment]
Btw, -
1. Why isn't the sagernet app not updated on F-droid?
2. Why isn't the wireguard plugin available on F-droid?

**Comment by nekohasekai** [comment]
Because F-Droid does not yet support Android SDK 31 so that we can’t compile

**Comment by liuxyon** [comment]
wireguard can't work

**Comment by CaKrome** [comment]
F-Droid now has support for API 31, FairEmail already released the first API 31 build on F-Droid.
