### ISSUE TITLE
[Feature request] Root support

### ISSUE THREAD

**Issue by dennis90a** [SagerNet/SagerNet#250]
With root support, we can use the app without using Android's VPN implementation. This way it could be faster and we could also be able to use other VPN applications (that don't have a SagerNet plugin, like some enterprise VPN from employer) together with SagerNet.

**Comment by nekohasekai** [comment]
Because F-Droid does not yet support Android SDK 31 so that we can’t compile

**Comment by dennis90a** [comment]
@nekohasekai Really sorry, didn't mean to spam, but there was only a bug report template. Is it ok if I create a new issue using the bug report template?
