### ISSUE TITLE
路由组中同时添加 domain 项和 ip 项会使路由无法生效

### ISSUE THREAD

**Issue by PaPerseller** [SagerNet/SagerNet#255]
例如新建路由组名为“绕过”，domain 项设置`geosite:cn`，ip 项设置`geoip:cn`，启用连接将不会报错，但此“绕过”路由组将不会生效。不知此为 bug 还是 feature? 按默认设置设两个路由组分别为domain和ip则分流正常。

**Comment by IIIlllIIllIIIll** [comment]
当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。即 domains 和 ip 规则需要分开使用。
https://www.v2fly.org/config/routing.html#ruleobject

**Comment by PaPerseller** [comment]
> 当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。即 `domains` 和 `ip` 规则需要分开使用。
> https://www.v2fly.org/config/routing.html#ruleobject

但一个路由组中既然同时提供了两个设置项，我认为在UI角度上是默认了同时设置并区分的操作。否则domain和ip应是在一个按钮中二选一来进行添加
![Screenshot_20210915-175315_AnXray](https://user-images.githubusercontent.com/16205434/133413232-27402378-b5d4-4468-b655-a7ff015bc7d9.png)
