### ISSUE TITLE
Apps are not routed correctly

### ISSUE THREAD

**Issue by ghost** [SagerNet/SagerNet#261]
### Describe the bug

Apps are not routed correctly.

### To Reproduce

1. Open sagernet(latest from play store), add cloudflare profile
2. Add another socks proxy for tor
3. Open route page, add route for chrome through tor
4. Add another route for instagram, through cloudflare
5. Error: gmail and other apps are also routed - sometimes through tor, and sometimes through cloudflare. Can be confirmed by using termux, and running `curl ifconfig.me`

### Debug Information

> About -> Export Debug Information

![Screenshot_20210920-083259_SagerNet](https://user-images.githubusercontent.com/88936537/133953611-a83d9669-02ad-46d1-af09-04105bdedfd3.png)
Couldn't find option

### Expected behavior

Expected only chrome to be routed through tor, and instagram to be routed through cloudflare, but other apps are routed as well.

### Smartphone (please complete the following information)

- Kernel version: 4.16
- Device: OnePlus 8T
- OS: ArrowOS - Android 10

**Comment by makintos90** [comment]
Invalid?

**Comment by makintos90** [comment]
Should I provide more information?
