### ISSUE TITLE
Use System DNS

### ISSUE THREAD

**Issue by ahbanavi** [SagerNet/SagerNet#262]
Hi.  
Is there any keyword I can use in Remote and Direct DNS fields to use default system DNS?  
The problem is when I'm home, I connect to my local Pihole DNS server that I set in the Wi-Fi connection, and when I'm out I use quad one DNS that I set in my LTE connection settings.  
Since there are two different situations, I have to manually changes the settings in Sagernet every time I arrive at home or leaving it.  
It would be very helpful if there is an option to use system DNS settings all the time.

**Comment by Hubedge** [comment]
+1

**Comment by cache444** [comment]
在设置中将https://1.0.0.1/dns-query改为localhost即可；也可以将远程DNS和直连DNS都改为localhost。

**Comment by ahbanavi** [comment]
> 
> 
> 在设置中将[https://1.0.0.1/dns-query改为localhost即可；也可以将远程DNS和直连DNS都改为localhost。](https://1.0.0.1/dns-query%E6%94%B9%E4%B8%BAlocalhost%E5%8D%B3%E5%8F%AF%EF%BC%9B%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%B0%86%E8%BF%9C%E7%A8%8BDNS%E5%92%8C%E7%9B%B4%E8%BF%9EDNS%E9%83%BD%E6%94%B9%E4%B8%BAlocalhost%E3%80%82)

It's not going to work.  
Because `localhost` means forward DNS queries to port 53 of localhost, not use system DNS settings.

**Comment by aria001** [comment]
> > 在设置中将[https://1.0.0.1/dns-query改为localhost即可；也可以将远程DNS和直连DNS都改为localhost。](https://1.0.0.1/dns-query%E6%94%B9%E4%B8%BAlocalhost%E5%8D%B3%E5%8F%AF%EF%BC%9B%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%B0%86%E8%BF%9C%E7%A8%8BDNS%E5%92%8C%E7%9B%B4%E8%BF%9EDNS%E9%83%BD%E6%94%B9%E4%B8%BAlocalhost%E3%80%82)
> 
> It's not going to work.
> Because `localhost` means forward DNS queries to port 53 of localhost, not use system DNS settings.

https://www.v2fly.org/en_US/config/dns.html#dnsobject
Read it and you'll know why localhost

**Comment by ahbanavi** [comment]
> 
> 
> > > 在设置中将[https://1.0.0.1/dns-query改为localhost即可；也可以将远程DNS和直连DNS都改为localhost。](https://1.0.0.1/dns-query%E6%94%B9%E4%B8%BAlocalhost%E5%8D%B3%E5%8F%AF%EF%BC%9B%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%B0%86%E8%BF%9C%E7%A8%8BDNS%E5%92%8C%E7%9B%B4%E8%BF%9EDNS%E9%83%BD%E6%94%B9%E4%B8%BAlocalhost%E3%80%82)
> > 
> > 
> > It's not going to work.
> > Because `localhost` means forward DNS queries to port 53 of localhost, not use system DNS settings.
> 
> https://www.v2fly.org/en_US/config/dns.html#dnsobject
> Read it and you'll know why localhost

I test it, but it didn't work.  

![image](https://user-images.githubusercontent.com/39927312/134640507-0b792df4-3eb1-4b58-9af8-8845ef6a2ccd.png)
![image](https://user-images.githubusercontent.com/39927312/134640532-645d8570-4a14-4f75-ba40-c0a525b49bda.png)

**Comment by cache444** [comment]
1. 关闭流量探测试试看
2. 检查是否在设备的设置中启用了私人DNS（如果启用了私人DNS，请关闭它再尝试）

SagerNet的核心是v2ray/fly，在v2ray/fly的文档中，localhost表示使用本机预设的DNS，你也可以理解为它本身就是动态的，也能解决你所描述的问题。我和你一样，但是我使用localhost是正常的、可用的。

**Comment by dyhkwong** [comment]
> I test it, but it didn't work.

Seems that native lookup returns IPv4-mapped IPv6 AAAA records instead of A records for A queries on some devices. May you send the output of `dig a www.google.com` using `localhost` on your device?

**Comment by ahbanavi** [comment]
> 
> 
> > I test it, but it didn't work.
> 
> Seems that native lookup returns IPv4-mapped IPv6 AAAA records instead of A records for A queries on some devices. May you send the output of `dig a www.google.com` using `localhost` on your device?

I don't know how to use dig on android, and termux seems to use 8.8.8.8 DNS server by default.  
I check my DNS servers logs, It didn't send any request to my DNS server when I start Sagernet.

**Comment by Hubedge** [comment]
> > > > 在设置中将[https://1.0.0.1/dns-query改为localhost即可；也可以将远程DNS和直连DNS都改为localhost。](https://1.0.0.1/dns-query%E6%94%B9%E4%B8%BAlocalhost%E5%8D%B3%E5%8F%AF%EF%BC%9B%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%B0%86%E8%BF%9C%E7%A8%8BDNS%E5%92%8C%E7%9B%B4%E8%BF%9EDNS%E9%83%BD%E6%94%B9%E4%B8%BAlocalhost%E3%80%82)
> > > 
> > > 
> > > It's not going to work.
> > > Because `localhost` means forward DNS queries to port 53 of localhost, not use system DNS settings.
> > 
> > 
> > https://www.v2fly.org/en_US/config/dns.html#dnsobject
> > Read it and you'll know why localhost
> 
> I test it, but it didn't work.

It works on my side. Try disabling `Enable DNS Routing`. Thanks @cache444

**Comment by ahbanavi** [comment]
> It works on my side. Try disabling `Enable DNS Routing`. Thanks @cache444

I test it with or without that option, still when I use `localhost` in DNS for remote or local or both, domains didn't resolve any longer.  
I think it might be OS or Device problem.  
My phone is Galaxy Note 9 with android 10.  
If is there a way that I provide logs, please let me know.

**Comment by Hubedge** [comment]
Further test seems to suggest setting DNS to `localhost` works only for the first few minutes. After that, `bypass` / `direct` destinations begin to fail due to DNS errors and after another few minutes `proxy` destinations fail too, possibly because DNS record of proxy server is time-out from cache and is unable to be resolved by localhost DNS.

**Comment by ahbanavi** [comment]
> 
> 
> Further test seems to suggest setting DNS to `localhost` works only for the first few minutes. After that, `bypass` / `direct` destinations begin to fail due to DNS errors and after another few minutes `proxy` destinations fail too, possibly because DNS record of proxy server expired and is unable to be resolved by localhost DNS.
> 
> For now, I will stick to default DNS setups.

So it's SagerNet bug? Then I think this issue should be labeled Bug than question.

**Comment by dmirubtsov** [comment]
> v2rayNG works properly

Sorry, checked v2rayNG again -- the same issue. I'm using shadowsocks+xray-plugin currently. Maybe it's device-specific bug(I see that @ahbanavi use Note 9 too) which appears with pure xray/v2ray? It's really strange
