### ISSUE TITLE
关于最新的几个版本无法使用的问题

### ISSUE THREAD

**Issue by stan0577** [SagerNet/SagerNet#273]
最新几个版本的sn和ax在miui12.5.5上无法使用，可以测试延迟，但连接后无法访问互联网。之前的版本（ax03系列）可以正常使用。
    希望尽快修复该问题。

**Comment by yanwh0311** [comment]
应该不是单纯是miui的问题，部分第三方rom也存在这个问题。
以下是复现bug的步骤：
1、清除app 的 storage 和 cache
2、打开app并添加节点，此时是可以正常使用的。
3、连接的情况下点开设置选项，此时会弹出提示：选项已更改，请重新加载以应用
4、重新连接后就连不上了
PS：只要不点开设置选项，都可以正常连接。
