### ISSUE TITLE
How to use Nebulo with SagerNet

### ISSUE THREAD

**Issue by makintos90** [SagerNet/SagerNet#276]
[Nebulo](https://github.com/Ch4t4r/Nebulo) is a app for DNS rules. I can block domains and even use it as an ad blocker. How can I use this with nebulo? I know that there exists a route for blocking ads, but nebulo supports hosts file, and even refreshes those every day or so.

**Comment by dmirubtsov** [comment]
@makintos90 I use dnscrypt/pihole on xray/v2ray server
