### ISSUE TITLE
0.1-beta9版本导入vmess链接错误

### ISSUE THREAD

**Issue by Smith1970** [SagerNet/SagerNet#31]
**Describe the bug**

从vmess链接导入的vmess节点原本传输层加密配置是tls，但导入sagernet后的配置传输层加密选项是none

**To Reproduce**

1. 在sagernet中导入一个带有tls传输层加密选项的vmess节点
2. 尝试连接该节点，发现无法连接
3. 查看该节点配置，发现传输层加密处是none
4. 将其改为tls，连接正常

**Expected behavior**

可以正常导入带有tls传输层加密选项的vmess节点链接

**Screenshots**

![Screenshot_20210430-174538_SSRRAY_1_1](https://user-images.githubusercontent.com/17473921/116679207-c8453000-a999-11eb-9755-9e07e6d1456d.png)

同一个vmess链接导入sagernet和另一个支持v2ray的客户端(ssrray)

**Smartphone (please complete the following information):**
 - OS: [Android9]

**Additional context**

https://github.com/SagerNet/SagerNet/issues/23#issuecomment-829960926

上面这个链接描述的问题是由导入vmess链接错误导致的，手动修改传输层加密选项为tls即可正常使用

**Comment by nekohasekai** [comment]
已经修复, 等gengxin

**Comment by nekohasekai** [comment]
已经修复
