### ISSUE TITLE
这个项目是anxay改名的么???希望能增加个使用前置代理的功能

### ISSUE THREAD

**Issue by wutongskype** [SagerNet/SagerNet#313]
希望能增加个使用前置代理的功能,
比如添加两个out服务器,
其中一个指定另一个为前置代理
在文档里就是下面这两个, 应该不难实现吧
https://xtls.github.io/config/outbound.html#proxysettingsobject
https://www.v2fly.org/config/outbounds.html#proxysettingsobject

**Comment by cupen** [comment]
> 希望能增加个使用前置代理的功能, 比如添加两个out服务器, 其中一个指定另一个为前置代理 在文档里就是下面这两个, 应该不难实现吧 https://xtls.github.io/config/outbound.html#proxysettingsobject https://www.v2fly.org/config/outbounds.html#proxysettingsobject

不难，弱弱觉得你随便提个 `PR` 就摆平了. :D

**Comment by arm64v8a** [comment]
功能与「链式代理」重复
