### ISSUE TITLE
[Feature Request] 请求增加对于wireguard协议的二维码支持

### ISSUE THREAD

**Issue by dev-techmoe** [SagerNet/SagerNet#315]
目前有不少的工具，比如 [WeeJeWel/wg-easy](https://github.com/WeeJeWel/wg-easy) ，都支持二维码配置文件输出，并使用[wg官方客户端](https://play.google.com/store/apps/details?id=com.wireguard.android)进行扫描
二维码内容就是wg的配置文件，ini格式，无任何编码
下面是一个二维码解析出来的内容例子

```ini
[Interface]
PrivateKey = pkey
Address = 10.0.0.1/24
DNS = 1.1.1.1

[Peer]
PublicKey = publickey
PresharedKey = presharedkey
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = ip:port
```

二维码图片示例 

https://user-images.githubusercontent.com/7919562/145196922-c00c4e28-e8a8-4765-ae39-1c7696fc79ff.png

因为这个格式目前官方客户端也在用，所以我觉得它应该可以作为wg协议官方的二维码格式来看待，所以说希望能够考虑实现一下这方面功能。

**Comment by nekohasekai** [comment]
理论上是支持的，如果无法使用请提交详细信息。

**Comment by nekohasekai** [comment]
图片示例中带有无效的 key，它应该是一个固定长度的 base64 字符串，但（WireGuard UAPI） 实际上需要的是 hex 字符串，这使解析失败。

**Comment by dev-techmoe** [comment]
> 图片示例中带有无效的 key，它应该是一个固定长度的 base64 字符串，但（WireGuard UAPI） 实际上需要的是 hex 字符串，这使解析失败。

测试了这个配置：

```ini
[Interface]
PrivateKey = oG4XmX6z091VadTB+gbIdo6RWmGJVDzq39D/rMUVdW8=
Address = 10.8.0.2/24
DNS = 223.5.5.5

[Peer]
PublicKey = oPbVNpJy9VUk43HsPuzqcVq/3DzTb4y/dqaBSYB4Xyo=
PresharedKey = aAXUr9IxZGWUFXYUWH+I80Ig+oCOKU4wONXWJdXdKZM=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 0.0.0.0:31234
```

生成图片：

https://user-images.githubusercontent.com/7919562/145203404-e7fc5a35-e4a8-4a19-b0a4-9e8c10f95fc7.png

SagerNet依然无法扫描，但wg官方客户端没问题并且正常连接。

上面的配置是我在本地开的wg实例，只把ip部分替换成了0.0.0.0。

**Comment by dev-techmoe** [comment]
[0.6-beta11](https://github.com/SagerNet/SagerNet/releases/tag/0.6-beta11) 测试扫码已经没有问题了，辛苦了
