### ISSUE TITLE
点击 路由 - 管理路由资源 闪退

### ISSUE THREAD

**Issue by Left024** [SagerNet/SagerNet#321]
[SagerNet Crash Report 6957696458489984460.log](https://github.com/SagerNet/SagerNet/files/7698871/SagerNet.Crash.Report.6957696458489984460.log)

**Comment by nekohasekai** [comment]
不应该无权访问应用数据目录。如果清空数据无效，请告知完整设备信息。

**Comment by Left024** [comment]
新安装的，之前没装过
手机是Pixel 5 Android 12 装了rikka全家桶但是没有对软件进行任何限制

清除数据，重装都试过了，点进去就闪退

**Comment by nekohasekai** [comment]
请检查禁用某个/某些模块是否能修复该问题。

**Comment by Left024** [comment]
![photo_2021-12-12_22-50-01](https://user-images.githubusercontent.com/20574903/145717182-b1a77c6f-e4e4-4e7c-b1b0-6be3038ed42b.jpg)
![photo_2021-12-12_22-50-11](https://user-images.githubusercontent.com/20574903/145717285-212f4777-049c-4bc2-a78c-b39943caf9ac.jpg)
![photo_2021-12-12_22-50-14](https://user-images.githubusercontent.com/20574903/145717288-436f0171-2e49-40a4-a500-9a5e605c236d.jpg)
模块都是刚需，如果是模块导致的闪退问题，那就算了，上图为我的模块列表

感谢您的耐心回复

**Comment by nekohasekai** [comment]
> 如果是模块导致的闪退问题

这需要您来测试，而不是我。

**Comment by Left024** [comment]
您误解我的意思了，我的意思是模块我都需要用，如果是模块导致的那我就不用这个软件了，提供模块列表也只是给个参考，不是说要您帮我测试。

**Comment by nekohasekai** [comment]
我的意思是让你测试一下。

**Comment by Left024** [comment]
1. 关闭所有模块，重启后依然闪退，清除数据后不再闪退
2. 逐个开启模块，重启；软件正常
3. 所有模块均开启，软件依然正常；此时清除数据，正常；重装，正常
