### ISSUE TITLE
无法使用域名访问纯IPv6网站

### ISSUE THREAD

**Issue by zyizhuo** [SagerNet/SagerNet#339]
修改#338 格式

### 描述问题

无法使用域名访问纯IPv6网站

### 如何复现

1.打开APP，使用默认设置。
2.导入任意可用的IPv6/IPv4双栈节点。
3.使用FireFox或系统浏览器访问纯IPv6网站。

### 调试信息

```SagerNet 0.6-rc02 (700) OSS
Date: 2022-01-03 04:40:05.869 UTC

OS_VERSION: 4.14.116
SDK_INT: 29
RELEASE: 10
ID: HUAWEIOCE-AN50
DISPLAY: OCE-AN50 2.0.0.218(C00E206R7P5)
INCREMENTAL: 102.0.0.218C00
SECURITY_PATCH: 2020-11-01
IS_DEBUGGABLE: 0
IS_EMULATOR: null
IS_TREBLE_ENABLED: true
TYPE: user
TAGS: release-keys

MANUFACTURER: HUAWEI
BRAND: HUAWEI
MODEL: OCE-AN50
PRODUCT: OCE-AN50
BOARD: OCE
HARDWARE: kirin990E
DEVICE: HWOCE-ML
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi

Settings: 

socksPort: 2080
portLocalDns: 6450
httpPort: 9080
transproxyPort: 9200
dnsHosts0: 
isAutoConnect: true
directBootAware: false
appTheme: 2
nightTheme: 0
serviceMode: vpn
tunImplementation: 0
appTrafficStatistics: false
profileTrafficStatistics: true
speedInterval: 1000
alwaysShowAddress: false
securityAdvisory: true
meteredNetwork: false
showDirectSpeed: false
showStopButton: false
allowAccess: false
proxyApps: false
bypassLanInCoreOnly: false
destinationOverride: false
resolveDestination: false
providerTrojan: 0
enableDnsRouting: false
disableDnsExpire: false
requireHttp: false
appendHttpProxy: true
requireTransproxy: false
transproxyMode: 0
connectionTestURL: https://api.v2fly.org/checkConnection.svgz
enableMux: false
enableMuxForAll: false
muxConcurrency: 8
tcpKeepAliveInterval: 15
trafficSniffing: false
domainStrategy: IPIfNonMatch
profileId: 1
bypassLan: true
directDns: https+local://dns.alidns.com/dns-query
rulesProvider: 1
ipv6Mode: 2
enablePcap: false
profileGroup: 1
enableLog: true
remoteDns: https://doh.google/dns-query
profileCurrent: 1
profileStarted: 1

Logcat: 

--------- beginning of main
01-03 12:39:59.353  6796  6796 E RtgSchedManager: endActivityTransaction: margin state not match
01-03 12:39:59.361  6796  6796 E RtgSchedManager: endActivityTransaction: margin state not match
```

### 预期行为

正常显示IPv6网页
![Screenshot_20220103_123149](https://user-images.githubusercontent.com/51268992/147899885-2b72b42d-8bbc-4c7e-ac91-3751b7509463.jpg)

### 屏幕截图

网页无法访问，疑似DNS解析失败。

![Screenshot_20220103_122847](https://user-images.githubusercontent.com/51268992/147899927-73918420-b648-4928-be2a-c7491022c799.jpg)

### 设备信息

- 内核版本: [4.14.116]
- 设备型号: [华为 Mate40E]
- 操作系统: [HarmonyOS 2.0.0 with Android 10Q (API29)]

### 附加上下文

PC端使用V2RayA可以正常访问，
使用V2RayNG时关闭流量探测可以访问，在这里也无法解决。

**Comment by nekohasekai** [comment]
不要乱动不懂的设置，清空数据重来。

**Comment by zyizhuo** [comment]
已经清空了好几次了😓就算全默认也是一样的效果。

**Comment by zyizhuo** [comment]
> 不要乱动不懂的设置，清空数据重来。

已经清空和重装几次。使用全默认设置也是一样的效果。

**Comment by nekohasekai** [comment]
你写的 doh.google 是什么网站？

**Comment by zyizhuo** [comment]
> 你写的 doh.google 是什么网站？

不好意思，打错了。之前这里用的是私人的nextdns地址（https://dns.nextdns.io/xxxxxx）。为了避免泄露就在日志改成谷歌，结果打错了。

**Comment by zyizhuo** [comment]
> 你写的 doh.google 是什么网站？

不好意思，打错了。之前这里用的是私人的nextdns地址（ https://dns.nextdns.io/xxxxxx ）。为了避免泄露就在日志随手改成谷歌，结果打错了。现在改回来了🥲。
但是我确认不是这里的问题。因为当时我看浏览器错误就认为是DNS问题，就尝试了多个DNS配置。包括清空数据后默认的、国内外都改成阿里、腾讯等等，结果都是上面这样。

**Comment by nekohasekai** [comment]
ipv6.baidu.com 只有 ipv4 解析。

**Comment by ag2s20150909** [comment]
https://www.cctv.com/

**Comment by zyizhuo** [comment]
> ipv6.baidu.com 只有 ipv4 解析。

开发者您好，这次使用最新版本测试“https://ipv6test.google.com/”与"https://ipv6.tsinghua.edu.cn/"。发现打开“使用本地DNS作为直连DNS”就可以正常访问了，问题已解决，多谢。

**Comment by txtyb** [comment]
ipv6 only节点，连接没有AAAA记录的网站，例如`github.com`，域名会被软件dns解析为A记录ipv4 ip，这使得远端服务器上的nat64+dns64配置被绕过而失效，导致网站无法访问。
