### ISSUE TITLE
[Feature Request] Ability to side load a root CA certificate

### ISSUE THREAD

**Issue by Explorare** [SagerNet/SagerNet#340]
I'm using BlackBerry PRIV, which ships with Android 6.0.1 and won't get any patch anymore. The DST Root CA X3 from Let's Encrypt has been expired on 2021-09-30. And my device didn't get the new root certificates, which cased all Trojan connections rely on that certificate won't work with certificate checking enabled. I've tried installing ISRG Root X1, ISRG Root X2, Let’s Encrypt R3 in user space for VPN / app usage, which didn't work for SagerNet.

So is it possible for SagerNet to add an option to side load root CA certificates inside the app just like Firefox did?

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/SagerNet/commit/29b1d0f4fc48c44ced51b02542c3792421f80840

**Comment by Explorare** [comment]
Just tested the 0.7-beta01 with **Trojan Provider** set to `V2Ray` and **Root CA Certificates Provider** to `Mozilla`, it didn't work for Trojan server with **Allow Insecure** `disabled`. I got the error io rw on closed pipe while I testing the connection. 

Also the log feature didn't work either with error `Invalid parameter tag.color to -v`.

Or maybe it's not worth the time to dig into this issue because of this crappy phone : (

**Comment by nekohasekai** [comment]
You can still export the logs by clicking the Send button. It may not be displayed directly because the system logcat version is too low.

**Comment by Explorare** [comment]
I've sent the log to you through email.

**Comment by nekohasekai** [comment]
`tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config`

You need to fill in the domain in the server address or the SNI, otherwise the client cannot verify the server.

**Comment by Explorare** [comment]
Thanks for your reply. I've checked the sub file and there are `skip-cert-verify: true` without SNI info in the config for trojan connections. The sub file is generated for Clash. And the equivalent key in SagerNet is `allowInsecure: true`. Clash.NET resolve the config with `skip-cert-verify: true` correctly but SagerNet didn't, and this causes the difference in behavior between Clash.NET and SagerNet. I could just replace all `skip-cert-verify` with `allowInsecure` but SagerNet only accept sub URL but not import from file. So I need to config every route manually. Luckily it only takes a few minutes. 

The new Firefox CA did fix the X509 issue as far as I know. Thanks for that.
Should I open a new issue for support `skip-cert-verify` support?

**Comment by nekohasekai** [comment]
Insecure nodes should not be subscribed.
