### ISSUE TITLE
hysteria service could not start after 0.7 BETA 01

### ISSUE THREAD

**Issue by zhea55** [SagerNet/SagerNet#342]
### To Reproduce

1. Start App.
2. Click connect button

### Screenshots
![Screenshot_20220107-202006_SagerNet](https://user-images.githubusercontent.com/7816215/148544979-13023efe-8194-4f4f-b0c0-9ea4615d2ef0.jpg)

**Comment by nekohasekai** [comment]
Should be fixed in [0.7-beta02](https://github.com/SagerNet/SagerNet/releases/tag/0.7-beta02)
