### ISSUE TITLE
[Feature request] Support zh_Hant_HK on Weblate

### ISSUE THREAD

**Issue by benathan** [SagerNet/SagerNet#358]
Currently on Weblate, SagerNet only allows a list of basic languages to be added in the translation.
![image](https://user-images.githubusercontent.com/42300169/151682085-7c5f530d-ea49-4ed1-8611-25a1ea5a3830.png)
It would be nice if **zh-Hant-HK** (Chinese (Traditional, Hong Kong)) are added to the list. zh-Hant are now very well maintained on Weblate and zh-Hant-HK are natively supported in Android. 
![image](https://user-images.githubusercontent.com/42300169/151682332-5a5852f9-d1e5-45a3-a924-73e2aff6f24e.png)
![image](https://user-images.githubusercontent.com/42300169/151682355-1c698828-6a76-44e9-9684-7824b5ab78af.png)
Please add the support, thank you.

**Comment by nekohasekai** [comment]
In android, it's zh-rHK, maybe it's a bug of weblate.

**Comment by nekohasekai** [comment]
https://hosted.weblate.org/projects/sagernet/app/zh_Hant_HK/#overview

**Comment by benathan** [comment]
Thank you
