### ISSUE TITLE
⚠️ Can't connect to PingTunnel (ICMP) without Root

### ISSUE THREAD

**Issue by Se7enstars** [SagerNet/SagerNet#360]
Hello guys, How to connect to PingTunnel without Root? 
When I add PingTunnel Server and Key, after click of connect button, it said about some directory SU (i think it ask me about root) but my phone haven't a Root. Pls fix this problem!
See DroidVPN there is available connect to ICMP without root. _Thanks in Advance!_

**Comment by hbakhtiyor** [comment]
without root would be nice, see droidvpn as well
