### ISSUE TITLE
build 问题

### ISSUE THREAD

**Issue by xujhindev** [SagerNet/SagerNet#364]
我clone了项目以后，导入到Android studio中，external 中的文推荐全是空白，请问我需要如何修改才能让项目跑起来呢？
![image](https://user-images.githubusercontent.com/95906086/153180062-5bcfca93-a20f-4364-86da-76c593337fac.png)

**Comment by LAziznezhad** [comment]
@xujhindev Project with path ':editorkit' not found in build 'editorkit'.
I have this problem, how to solve it?
