### ISSUE TITLE
Broken NaïveProxy Support from 0.6 BETA 13

### ISSUE THREAD

**Issue by vcheckzen** [SagerNet/SagerNet#376]
### Describe the bug

Can not connect to NaïveProxy server with both https and quic protocols using 0.6 BETA 13 and later versions of SagerNet.

### To Reproduce

1. Install SagerNet (0.7 RC 08) and NaïveProxy Plugin (98.0.4758.80-2)
2. Import a server
3. Connect to the server
4. Check the connectivity
5. See the `Failed: Timeout` hint

### Debug Information

[SagerNet 8630443428840109259.log](https://github.com/SagerNet/SagerNet/files/8108179/SagerNet.8630443428840109259.log)

### Expected behavior

Can use NaïveProxy nodes normally.

### Smartphone

- Kernel version: [4.4.153]
- Device: [MI MIX 2]
- OS: [Android 9]

### Additional context

I tested older versions of SagerNet, 0.6 BETA 12 works properly, the later versions all suffer from the above problem. I found from the log that 0.6 BETA 13 changed the NaïveProxy config format to make it connect through v2ray, and may be that is the root reason.

**Comment by nekohasekai** [comment]
Can't reproduce (both https and quic).
Your logs show that you are trying to connect to a non-existing domain.

**Comment by vcheckzen** [comment]
Excuse me for the bothring. The final reason is that I didn't publish the dns record to a nameserver but adding a record to the router's hosts file which my phone connected the wifi the router sending out, but the certificate is valid.

With version 0.6 BETA 12, there is no problem using this way, and with version 0.7 RC 08, after opening `Use Local DNS as Direct DNS` from SagerNet setting, it works like a charm too.

Appreciate you and your excellent work, have a good day.
