### ISSUE TITLE
右下角纸飞机图标点击后自动反复开关

### ISSUE THREAD

**Issue by Jimmisama** [SagerNet/SagerNet#381]
### 描述问题
部分节点点击右下角纸飞机后会反复开关，伴随顶部状态栏VPN钥匙图标一起“闪现” 停下来的办法是通过任务管理强制退出
### 如何复现

选好节点，点击右下角纸飞机

### 调试信息
[SagerNet 5931698174144931456.log](https://github.com/SagerNet/SagerNet/files/8127636/SagerNet.5931698174144931456.log)

### 预期行为

右下角纸飞机按钮反复开关伴随顶部状态栏小钥匙图标反复闪现

### 屏幕截图

如果适用, 请添加屏幕截图以帮助解释您的问题.

### 设备信息

- 内核版本: 5.10.43-android12-9-00007-g9771767708df-ab8009062
- 设备型号: Google Pixel 6 Pro
- 操作系统: Android 12

### 附加上下文

部分节点不会，同设备点击URLtest会闪退

**Comment by jelly0925** [comment]
昨晚更新到0.7-rc09我手机也出现同样的问题，安卓11，节点类型trojan和ss节点反复重启，目前只能回退到0.7-rc08。

**Comment by wongwengtim** [comment]
目前發現與使用本地DNS有關：
在0.7-rc09當開啟使用本地DNS或填入localhost連接vmess時，SagerNet會反覆重連。

**Comment by Jimmisama** [comment]
新版本已经修复
