### ISSUE TITLE
Improvement Suggestions

### ISSUE THREAD

**Issue by idnsunset** [SagerNet/SagerNet#394]
**It is not exactly a bug report but suggestions for functionality improvement. Sorry for opening a bug report but I don't see any issue template that fits something like function requests.**

### Describe the bug

* Multiple nodes selection. If I have hundreds of nodes, it would be terrible to delete them one by one.
* Configuration export. I see in some screenshots an upper arrow icon at the top bar that exports the configuration, however, I don't actually see it on my phone. 

### To Reproduce

Normal operations on configuration page.

### Debug Information

N/A

### Expected behavior

Long press on one node, and then short press on another node to select a range of nodes for deletion or configuration export.  I usually only want to export the configuration for a range of nodes of good quality instead of all of them.

### Smartphone (please complete the following information)

- Kernel version: 4.14.243
- Device: Pixel 5
- OS: Android 12

### Additional context

I tried both SagerNet 0.7rc10 and AnXray 0.4rc6, neither of them meets my requirements described above.

**Comment by nekohasekai** [comment]
Pull request welcome
