### ISSUE TITLE
[Feature Request] Add a button to directly delete all "Unavailable" proxies. 

### ISSUE THREAD

**Issue by Mahdi-Mansouri** [SagerNet/SagerNet#399]
In a lot of situations, I have a proxy list (maybe 1000 proxies) and I check them using URLTest to see if they are blocked by ISP or not. And maybe 200 of them doesn't work. I can't delete all 200 blocked proxies one by one. Sometimes I want to share just "working" proxies, not blocked ones.

So, in this situation, we need something to delete all "Unavailable" proxies to have a better experience.

**Comment by nekohasekai** [comment]
This is not what the group is designed for.
