### ISSUE TITLE
Ookla Speedtest app fails to measure upload speed

### ISSUE THREAD

**Issue by Mo3M** [SagerNet/SagerNet#403]
**Before submitting an issue, please make sure you are using the latest version of SagerNet.**

### Describe the bug

Trying to measure dl/up speed by Ookla Speedtest app fails when it comes to measuring upload speed. Although Speedtest correctly measures dl speed, it stops measuring upload speed at the early stage and shows a msg:
"Error.
Test failed to complete. Please check your connection and try again."

Reinstalling SN didn't help so I reverted back to SN v0.7 rc07 and it works now.

### To Reproduce

1. I chose a shadowsocks server in SN
2. Start the VPN
3. Ookla Speedtest fails to measure upload speed

### Screenshots

[SagerNet 4728165798843540890.log](https://github.com/SagerNet/SagerNet/files/8270063/SagerNet.4728165798843540890.log)

- Kernel version: 4.9.179-perf+
- Device: OnePlus 6T
- OS: Android 10

**Comment by nekohasekai** [comment]
Your log is useless, try to make a new one.

**Comment by Mo3M** [comment]
I don't know how the new log will be different. The SN rc11 doesn't crash but somehow it blocks upload entirely.

I created another log:
What I did are as follows:
I uploaded 2 files. 
- First one was a 207 bytes in size which uploaded successfully.
- Second one was 117 kbytes which couldn't be uploaded.
Hope it helps.

[SagerNet 1492385113120953839.log](https://github.com/SagerNet/SagerNet/files/8279545/SagerNet.1492385113120953839.log)

**Comment by Mo3M** [comment]
The same shadowsocks server works in rc07 and V2rayNG.

**Comment by Mo3M** [comment]
@nekohasekai 
Did the new log help?
The upload is almost entirely blocked system-wide.

**Comment by kvmb** [comment]
It seems that only Shadwosocks has this problem, it's normal in SN-rc-10 , started appearing in rc-11, speedtest unable to test upload speed, and I test upload files in telegram and also failed, the log is full of errors like below, so I didn't upload the log, I also saw those errors in Mo3M's log, maybe it's the reason of the problem? 

03-22 09:04:50.086 19409 19453 I v2ray-core: proxy/shadowsocks: tunneling request to tcp:149.154.175.54:5222 via tcp:ss-server-ip:port
03-22 09:04:50.102 19409 23690 W v2ray-core: app/dispatcher: default route for tcp:149.154.175.54:443
03-22 09:04:50.102 19409 23690 I v2ray-core: transport/internet/tcp: dialing TCP to tcp:ss-server-ip:port
03-22 09:04:50.308 19409 23351 I v2ray-core: proxy/shadowsocks: tunneling request to tcp:149.154.175.54:443 via tcp:ss-server-ip:port
03-22 09:04:50.427 19409 23721 I v2ray-core: app/proxyman/outbound: failed to process outbound traffic > proxy/shadowsocks: connection ends > proxy/shadowsocks: failed to read IV > read tcp 192.168.1.100:48246->ss-server-ip:port: read: connection reset by peer

**Comment by Mo3M** [comment]
Thanks @kvmb. 😃👍
The upload bug is now gone thanks to the @nekohasekai 😃
But SN still sometimes crashes when doing a URL Test.

#385 

The only workaround that sometimes helps is to force stop SN and clear cache.
