### ISSUE TITLE
crashes when editing profile

### ISSUE THREAD

**Issue by samlux04** [SagerNet/SagerNet#419]
**Before submitting an issue, please make sure you are using the latest version of SagerNet.**

### Describe the bug

After tapping the edit button it immediately crashes.

### To Reproduce

1. Tap edit button(pencil icon)

### Debug Information

[SagerNet Crash Report 8502714351393249777.log](https://github.com/SagerNet/SagerNet/files/8384360/SagerNet.Crash.Report.8502714351393249777.log)

### Expected behavior

Edit window should appear

### Smartphone (please complete the following information)

- In the log file

**Comment by samlux04** [comment]
It seems only happens with trojan profile. Please do the needful. thank you sir.

**Comment by Hubedge** [comment]
Same crashing issue here when trying to edit/add `trojan` profile.

**Comment by samlux04** [comment]
it's fixed in beta 02. thanks.
