### ISSUE TITLE
在分应用代理，选择中国应用时闪退

### ISSUE THREAD

**Issue by detiam** [SagerNet/SagerNet#42]
**Describe the bug**
如题

**To Reproduce**
路由设置-分应用代理-在右上角选项中选择扫描中国应用，在扫描途中闪退

**Logcat**
https://pastebin.com/raw/p9tcFikp

**Expected behavior**
没有闪退

**Screenshots**
无

**Smartphone (please complete the following information):**
 - Device: Unihertz Jelly2
 - OS: Android10

**应用版本**
 - Version: 0.1-beta13

**Comment by nekohasekai** [comment]
应该已经修复了。
