### ISSUE TITLE
[ Feature Request ] 'V2rayN compatible format' feature while export from 'Subscription Group'

### ISSUE THREAD

**Issue by beyond-far** [SagerNet/SagerNet#424]
**Before submitting an issue, please make sure you are using the latest version of SagerNet.**
latest 0.8 beta 01

### Describe the bug

optional 'V2rayN compatible format' is available while export (to clipboard/file) from each node
but NOT available while export from 'Subscription Group' (export all nodes, not share subscription)

### To Reproduce

1. Go to 'Group'
2. Click on '...' of a 'Subscription Group'
3. Choose 'Export...'
4. No compatible option for export to clipboard / file either

### Expected behavior

It's better to have 'V2rayN' compatible feature presented since most openwr-wrt apps support this legacy format only.

**Comment by nekohasekai** [comment]
Submit your request to v2rayN

**Comment by beyond-far** [comment]
Thanks for your response, but this thread is nothing to do with v2rayN 

what I mentioned was popular openwrt app 'luci-app-ssr-plus'

please check this subscription parsing script:
https://github.com/kenzok8/openwrt-packages/blob/master/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

the vmess link exported from v2rayNG android app will be identified as VMESS uri

while

the vmess link exported from SagerNet android app (for group export action only) seems more like VLESS uri but actually not, which may cause parsing failure.

truly v2ray/v2fly developers refused to draft any standard for vmess (like SIP008 for shadowsocks), which uri format to support is definitely decided by app developer.

but considering openwrt app were so popular for years, it's reasonable to support another format -- and it is actually already builded in SagerNet(for single server export action), it will be great if could be available in group export action also.
