### ISSUE TITLE
Manual or editing subsciption Trojan crashes Sagernet App

### ISSUE THREAD

**Issue by essoojay** [SagerNet/SagerNet#427]
Trying to create new or editing pasted Trojan subscription crashes Sagernet altogether. Tried 3 different android phones. 

Phones: 
Samsung Fold 3
Pixel 6
Xperia 5 ii

Android Version: 12

Sagernet 
Version 0.8-beta01

Please check this.

**Comment by Hubedge** [comment]
dup #419
