### ISSUE TITLE
vless+xtls 协议 纯ipv6+nat64 vps 连接后无法上网，测试显示connect closed

### ISSUE THREAD

**Issue by detiam** [SagerNet/SagerNet#43]
**Describe the bug**
vless+xtls 协议 纯ipv6+nat64 vps 连接后无法上网，测试显示connect closed
在win10上使用qv2ray内核为xray1.4.2正常使用，手机为扫码导入

**To Reproduce**
主界面右上角添加-扫描二维码-点击添加的链接-左下角纸飞机启动-点击测试-connect closed-右边栏-路由-DNS设置-更改远程dns为“https://[2606:4700:4700::1111]/dns-query”-重新连接并测试-connect closed
（之后DNS设置只输入[2606:4700:4700::1111]，2606:4700:4700::1111（无括号）同错误

**Logcat**
https://pastebin.com/raw/r7r7P2nq

**Expected behavior**
正常连接

**Screenshots**
![photo_2021-05-01_14-49-56](https://user-images.githubusercontent.com/44510779/116774071-8a750400-aa8c-11eb-85dc-bfe4b7747244.jpg)

**Smartphone (please complete the following information):**
 - Device: Unihertz Jelly2
 - OS: Android10

**应用版本**
 - Version: 0.1-beta13

**Comment by nekohasekai** [comment]
应该已经修复。

**Comment by detiam** [comment]
> 
> 
> 应该已经修复。

最新版本（0.1-beta17）问题仍然存在，这是按照上述步骤操作后生成的log
https://pastebin.com/raw/izs2fLwD
v2rayng可以连接但必须开启allowinsecure和ipv6优先才能连接，不过我不确定是否是ssl设置问题，因为检查后在使用qv2ray时其实并没有开启allowinsecure，浏览器访问正常并且系统内没有安装对应证书。这也许是core的问题？但似乎只在安卓上出现
请问是否需要节点信息协助复现？
