### ISSUE TITLE
Question about SN Privacy & Request

### ISSUE THREAD

**Issue by Shikopat** [SagerNet/SagerNet#438]
Hello

Recently, I've Installed "App Manager" and found these three permissions that are strange and worrying for many other users and me. 

![photo_2022-04-10_11-22-52](https://user-images.githubusercontent.com/85629762/162606258-a6460a65-2ac2-4723-b642-2502a52586ee.jpg)

I respectfully ask you what the reason for using these three accesses is? And whether you can disable them in future updates? Or at least the user can disable them?

Regards.

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/SagerNet/wiki/Privacy-policy
