### ISSUE TITLE
unable to detect proxies from clash Subscription url

### ISSUE THREAD

**Issue by Kookemoon** [SagerNet/SagerNet#44]
**Describe the bug**
i have issue with this url subscription (for clash) :
https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.yml

after I enter that url in "Group" section, it shows http proxies in list  (v0.1-beta9)
but in version 0.1-beta13, list of new group is Empty after I enter that url in "Group",even I press "update" button ! but I have no problem with "Clash for Android". for using that url subscription!

**Logcat**
Export it yourself :)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: A71 4G Samsubg (SM-A715F/DS)
 - OS: Android 11
 - Version 0.1-beta13

**Additional context**

**Comment by nekohasekai** [comment]
It should have been fixed.
