### ISSUE TITLE
uri export from groups not compatible with luci-app-ssr-plu

### ISSUE THREAD

**Issue by beyond-far** [SagerNet/SagerNet#441]
**Before submitting an issue, please make sure you are using the latest version of SagerNet.**
YES

### Describe the bug

uri export from groups not compatible with luci-app-ssr-plus

please check this subscription parsing script:
https://github.com/kenzok8/openwrt-packages/blob/master/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

the vmess link exported from v2rayNG android app will be identified as VMESS uri

while

the vmess link exported from SagerNet android app (for group export action only) seems more like VLESS uri but actually not, which may cause parsing failure.

### To Reproduce

1.Go to 'Group'
2.Click on '...' of a 'Subscription Group'
3.Choose 'Export...'
4.No compatible option for export to clipboard / file either
5.paste exported uri to subscribe field of openwrt luci-app-ssr-plu
6.no items found, parsing failed

### Expected behavior

truly v2ray/v2fly developers refused to draft any standard for vmess (like SIP008 for shadowsocks), which uri format to support is definitely decided by app developer.

but considering openwrt app were so popular for years, it's reasonable to support another format -- and it is actually already builded in SagerNet(for single server export action), it will be great if could be available in group export action also.

**Comment by nekohasekai** [comment]
That's basically a Chinese-style software, if you need an outdated or deprecated protocol, just fork and add it yourself
