### ISSUE TITLE
Brook WSSserver Not working

### ISSUE THREAD

**Issue by khafan11** [SagerNet/SagerNet#444]
### Describe the bug

Brook WSS Server not Connected with Sagernet But same Brook Address is working with brook client 

### Debug Information

```
bionic_open_tzdata_path: ANDROID_DATA not set!
bionic_open_tzdata_path: ANDROID_ROOT not set!
--------- beginning of main
04-16 13:25:00.946 +0000 31233 31233 E Choreographer: skip doframe for io.nekohasekai.sagernet
--------- beginning of system
04-16 13:26:11.657 +0000 28555 28555 I GuardedProcessPool: start process: /data/app/io.nekohasekai.sagernet.plugin.brook-1/lib/arm64/libbrook.so wssclient --wssserver wss://xx.xx.xx:42037 --serverAddress 127.0.0.1:42037 --password xxx --socks5 127.0.0.1:41524
04-16 13:26:11.692 +0000 28555 32663 E libbrook: WARNING: linker: /data/app/io.nekohasekai.sagernet.plugin.brook-1/lib/arm64/libbrook.so: unsupported flags DT_FLAGS_1=0x8000001
04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
04-16 13:26:39.844 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
04-16 13:26:39.844 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
```

### Smartphone 

- Device: [Meizu M6 Note]
- OS: [Flyme 8.0.5.0A. Android 7.1.2]

### Additional context

this wssserver wss://xx.xx.xx:42037  that i saw in log its weird ! port should be 443 ! not 42037 !

**Comment by SoheilShahbazian** [comment]
> ### Describe the bug
> Brook WSS Server not Connected with Sagernet But same Brook Address is working with brook client
> 
> ### Debug Information
> ```
> bionic_open_tzdata_path: ANDROID_DATA not set!
> bionic_open_tzdata_path: ANDROID_ROOT not set!
> --------- beginning of main
> 04-16 13:25:00.946 +0000 31233 31233 E Choreographer: skip doframe for io.nekohasekai.sagernet
> --------- beginning of system
> 04-16 13:26:11.657 +0000 28555 28555 I GuardedProcessPool: start process: /data/app/io.nekohasekai.sagernet.plugin.brook-1/lib/arm64/libbrook.so wssclient --wssserver wss://xx.xx.xx:42037 --serverAddress 127.0.0.1:42037 --password xxx --socks5 127.0.0.1:41524
> 04-16 13:26:11.692 +0000 28555 32663 E libbrook: WARNING: linker: /data/app/io.nekohasekai.sagernet.plugin.brook-1/lib/arm64/libbrook.so: unsupported flags DT_FLAGS_1=0x8000001
> 04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
> 04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
> 04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
> 04-16 13:26:33.824 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
> 04-16 13:26:39.844 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
> 04-16 13:26:39.844 +0000 31233 31233 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
> ```
> 
> ### Smartphone
> * Device: [Meizu M6 Note]
> * OS: [Flyme 8.0.5.0A. Android 7.1.2]
> 
> ### Additional context
> this wssserver wss://xx.xx.xx:42037 that i saw in log its weird ! port should be 443 ! not 42037 !

I have same problem
