### ISSUE TITLE
dns的tls模式不支持自定义端口吗？

### ISSUE THREAD

**Issue by viagram** [SagerNet/SagerNet#445]
tls默认端口是853
我一个新IP用不到一天，tls的853端口就被墙了，改用其它端口后，dig可以查到结果，但SagerNet貌似不支持tls://1.1.1.1:1153这种非默认端口的查询

**Comment by viagram** [comment]
dns顺便也支持一下DoQ吧

**Comment by Mo3M** [comment]
I'd been experiencing several problems like crashes/ time-outs/ not being able to connect for quite some time and finally I gave up on SN. For the past two weeks I've been using another fork. But if you insist on using SN, I recommend installing 0.8 beta 1 or 0.7 rc10 or older versions instead they were less buggy.

**Comment by viagram** [comment]
> 

thanks

**Comment by viagram** [comment]
> I'd been experiencing several problems like crashes/ time-outs/ not being able to connect for quite some time and finally I gave up on SN. For the past two weeks I've been using another fork. But if you insist on using SN, I recommend installing 0.8 beta 1 or 0.7 rc10 or older versions instead they were less buggy.

thanks
