### ISSUE TITLE
SIP008订阅刷新只显示一个配置

### ISSUE THREAD

**Issue by yiguihai11** [SagerNet/SagerNet#446]
我不确定这个是不是BUG。
这是我的订阅链接
```https://mikutap.ml/subscriptions.php```
无论怎么刷新都只显示一个配置，我在官方安卓版是正常的。
难道是返回格式有问题吗？

**Comment by nekohasekai** [comment]
http://shadowsocks.org/en/wiki/SIP008-Online-Configuration-Delivery.html

Your server must have a UUID when the official client is compatible with a lot of shit.
