### ISSUE TITLE
ability to add Geoip:ir for custom rules

### ISSUE THREAD

**Issue by Kookemoon** [SagerNet/SagerNet#45]
1.Ability  to add geoip:ir for bypassing rules, & ability to import or enter "Custom rules" like v2rayNG.

1. Ability to import url for "ACL Update" like this open-source app for rules:
https://github.com/xxf098/shadowsocksr-v2ray-trojan-android

3. Ability to add "Front Proxy" that supports Socks5 & HTTP(s) proxies like this open-source app:
https://github.com/xxf098/shadowsocksr-v2ray-trojan-android

**Comment by nekohasekai** [comment]
#22
