### ISSUE TITLE
手机重启后，如果路由中仍包含 `geosite:apple-cn` 等 `Loyalsoldier/v2ray-rules-dat` 中特有的域名分类，则会报错

### ISSUE THREAD

**Issue by FlandiaYingman** [SagerNet/SagerNet#463]
### Describe the bug

手机重启后，如果路由中仍包含 `geosite:apple-cn` 等 `Loyalsoldier/v2ray-rules-dat` 中特有的域名分类，则会报错。

### To Reproduce

1. Install the latest version of SagerNet.
2. 在设置中，将“路由信息更新源”改为 `Loyalsoldier/v2ray-rules-dat`。
3. 在路由——管理路由资源中，更新路由资源。
4. 添加一个路由规则，其中包含 `geosite:apple-cn`。
5. 添加一个服务器配置（任意），并启动。
6. **服务正常启动了。**
7. 重启手机。
8. 打开 SagerNet，启动服务器配置。
9. **服务启动失败了。**

### Debug Information

[SagerNet 3650376035574169190.log](https://github.com/SagerNet/SagerNet/files/8684462/SagerNet.3650376035574169190.log)

### Expected behavior

应为正常启动服务。

### Screenshots

重启前：

![EDDD6EDAFD60496166EDD13EBCB082E1](https://user-images.githubusercontent.com/9929037/168220470-d60d689a-9525-431d-a111-10bb93c3ce8a.jpg)

重启后；

![9982D996B1AE3DF06CB62C7E429A95B4](https://user-images.githubusercontent.com/9929037/168220682-9ede4d08-4a27-4de9-8f43-af21771977b4.jpg)

### Smartphone (please complete the following information)

- Kernel version: 5.10.66
- Device: Redmi K50
- OS: MIUI 13.0.13 Android 12

### Additional context

在日志中看到了类似 `SQLException` 的错误 stacktrace，猜想是手机重启后某个持久化部分出错了。

重置所有数据后，一切恢复正常。

**Comment by zzColin** [comment]
确认存在同样的重启后挂掉的问题，Android 11，一加氢 OS。

**Comment by pureair** [comment]
同样的问题
使用Official源，Route设置里添加规则domian栏填写geosite:gfw，保存后运行提示geosite.dat中找不到list gwf；
使用Loyalsoldier源，Route设置里添加规则domian栏填写geosite:gfw，保存后运行提示geosite.dat中找不到list gwf；
使用Loyalsoldier源，Route设置里添加规则domian栏填写geosite:greatfire，outbound栏填写Proxy，保存后运行不报错，但是实际上规则不生效。

**Comment by CoelacanthusHex** [comment]
> 同样的问题 使用Official源，Route设置里添加规则domian栏填写geosite:gfw，保存后运行提示geosite.dat中找不到list gwf； 使用Loyalsoldier源，Route设置里添加规则domian栏填写geosite:gfw，保存后运行提示geosite.dat中找不到list gwf； 使用Loyalsoldier源，Route设置里添加规则domian栏填写geosite:greatfire，outbound栏填写Proxy，保存后运行不报错，但是实际上规则不生效。

遇到同样问题

**Comment by lychichem** [comment]
您哪里已完成了@nekohasekai ，我一年后这问题还存在，烦请您修一修吧
