### ISSUE TITLE
URL Test测试节点过多闪退

### ISSUE THREAD

**Issue by jp5865** [SagerNet/SagerNet#489]
### 版本
0.8-rc02
### 描述问题
URL Test测试节点过多闪退

### 如何复现
1.[疑似触发]开启日志调试
2.测试超过60个节点

### 调试信息
[SagerNet 3684760602006423320.log](https://github.com/SagerNet/SagerNet/files/8948876/SagerNet.3684760602006423320.log)

 ### 设备信息
- 内核版本: 4.9.227-perf+
- 设备型号: oppo reno
- 操作系统: ColorOS11.1

**Comment by hfdem** [comment]
同样的问题
