### ISSUE TITLE
sagernet 不识别 trojan 链接中的 allowInsecure=1

### ISSUE THREAD

**Issue by sommio** [SagerNet/SagerNet#491]
> 请于下方括号中填写 y 以确认.

(y) 本人 sommio 为 SagerNet 0.8-rc04 之用户，并希望提交错误报告.

(y) 我理解 Project S 作者为业余开发者, 对计算机科学与网络通信的研究尚不充分, 没有任何专业支持为我提供. 如果可能, 我将自己解决问题并提交拉取请求.

(y) 我理解 SagerNet 为自由软件且没有非自由依赖, 我有发布、研究、修改和改进软件的自由, 但不得将修改版本作为专有软件发布 (包括不发布或更新源代码、混淆源代码、引入专有依赖).

(y) 我理解 SagerNet 为免费发行之软件, 除非另有书面说明, 全部的风险, 如绕过网络审查产生的以下法律的风险, 且其中一些可能造成财产损失甚至生命危险 (均有真实事件), 都由您来承担:

* 教育训诫
* 依法控制
* 拘留
* 免职
* 传唤警告
* 执行指定居所监视居住
* 警告处罚
* 拘役
* 有期徒刑
* 不公开审理

---

### 描述问题

Sagetnet 导入 trojan:// 链接时无法识别到 allowInsecure=1，但这在 fork 项目 Matsuri 中是正常的

### 如何复现

1. 从剪贴版导入 trojan://test@1.1.1.1:1?allowInsecure=1#test

### 预期行为

Sagetnet 正确识别到 allowInsecure=1 禁用证书检查

### 设备信息

- 内核版本: [4.14.116]
- 设备型号: [HONOR HLK-AL00]
- 操作系统: [Harmory OS 2.0.0 Android 10]

**Comment by nekohasekai** [comment]
这是垃圾应用的私有格式，官方是不承认的。（并且不安全的格式始终不应该被分享）

**Comment by sommio** [comment]
> > 请于下方括号中填写 y 以确认.
> 
> (y) 本人 sommio 为 SagerNet 0.8-rc04 之用户，并希望提交错误报告.
> 
> (y) 我理解 Project S 作者为业余开发者, 对计算机科学与网络通信的研究尚不充分, 没有任何专业支持为我提供. 如果可能, 我将自己解决问题并提交拉取请求.
> 
> (y) 我理解 SagerNet 为自由软件且没有非自由依赖, 我有发布、研究、修改和改进软件的自由, 但不得将修改版本作为专有软件发布 (包括不发布或更新源代码、混淆源代码、引入专有依赖).
> 
> (y) 我理解 SagerNet 为免费发行之软件, 除非另有书面说明, 全部的风险, 如绕过网络审查产生的以下法律的风险, 且其中一些可能造成财产损失甚至生命危险 (均有真实事件), 都由您来承担:
> 
> * 教育训诫
> * 依法控制
> * 拘留
> * 免职
> * 传唤警告
> * 执行指定居所监视居住
> * 警告处罚
> * 拘役
> * 有期徒刑
> * 不公开审理
> 
> ### 描述问题
> Sagetnet 导入 trojan:// 链接时无法识别到 allowInsecure=1，但这在 fork 项目 Matsuri 中是正常的
> 
> ### 如何复现
> 1. 从剪贴版导入 trojan://test@1.1.1.1:1?allowInsecure=1#test
> 
> ### 预期行为
> Sagetnet 正确识别到 allowInsecure=1 禁用证书检查
