### ISSUE TITLE
Do you support adding a new protocol and plugin?

### ISSUE THREAD

**Issue by enfein** [SagerNet/SagerNet#492]
Hello SagerNet community,

I have an open source socks5 proxy project called [mieru](https://github.com/enfein/mieru). It supports PC, Mac and Linux. I would like to make mieru available to android platform. Given SagerNet has a rich feature set, it can bring more value to users if mieru can run with SagerNet, vs an app made from scratch.

I want to hear community's opinion on this. Do you open to a new protocol and plugin? I can take the responsibility of development and maintenance over a long term.

Thank you.

**Comment by nekohasekai** [comment]
Hi, you can contact [my telegram](https://t.me/attachBaseContext) for more discussions if you want.

**Comment by nekohasekai** [comment]
[mieru-plugin-1.5.0-arm64-v8a.apk.zip](https://github.com/SagerNet/SagerNet/files/8983939/mieru-plugin-1.5.0-arm64-v8a.zip)
[SN-0.8-rc04-arm64-v8a-debug.apk.zip](https://github.com/SagerNet/SagerNet/files/8983950/SN-0.8-rc04-arm64-v8a-debug.zip)

Ready for test.

**Comment by enfein** [comment]
Thank you Sekai.

Using telegram in China is risky. I am evaluating the security of registering and operating telegram with a foreign number. This can take a while until I make the decision. In the meanwhile, I will go through source code and take a look at examples from existing plugins. I will contact you using telegram, or here if I believe using telegram is dangerous.

**Comment by nekohasekai** [comment]
See: https://github.com/SagerNet/SagerNet/tree/dev-mieru
