### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by legendtang** [SagerNet/SagerNet#493]
**Before submitting an issue, please make sure you are using the latest version of SagerNet.**

### Describe the bug

Starting any proxy, SagerNet cannot create/access SQLite database somewhere that does not exist causing crashes. The constant crash finally results in a background service stop.

### To Reproduce

Just starting the proxy

### Debug Information

[SagerNet 6974969005026782290.log](https://github.com/SagerNet/SagerNet/files/8986964/SagerNet.6974969005026782290.log)

### Expected behavior

No crashes

### Smartphone (please complete the following information)

- Kernel version: 4.19.157
- Device: Redmi K40
- OS: Android 12

### Additional context

The problem is reproducible on SagerNet 0.8.x, even on the latest 0.8.1-beta01

**Comment by nekohasekai** [comment]
Your log is incomplete

**Comment by nekohasekai** [comment]
Can't reproduce on Android 12 emulator, maybe a vendor issue.

**Comment by nekohasekai** [comment]
I think it's the logs produced by the old app being kept by logcat. And you may just encounter the app being killed by miui.
