### ISSUE TITLE
SagerNet.kt Unresolved reference: go

### ISSUE THREAD

**Issue by enfein** [SagerNet/SagerNet#495]
### Describe the bug

After clone the project, I am unable to build the app with android studio.

### To Reproduce

Clone SagerNet git repository with all submodules. Open the project in android studio. Click Build -> Make Module 'SagerNet.app'. After a while it returns error

```
SagerNet/app/src/main/java/io/nekohasekai/sagernet/SagerNet.kt: (47, 8): Unresolved reference: go
```

### Debug Information

N/A

### Expected behavior

Either the project should be able to build with standard tools and procedures, or a detailed document needs to be provided to set up required components.

### Screenshots

N/A

### Smartphone (please complete the following information)

N/A

### Additional context

N/A

**Comment by nekohasekai** [comment]
Check out the github action workflow file to know how to compile.

**Comment by enfein** [comment]
OK that works. BTW, why do you try to [power off](https://github.com/SagerNet/SagerNet/blob/c6c5dc733d1bde8b1417854098c0caf52c5f706a/buildSrc/src/main/kotlin/Helpers.kt#L258) my machine when I build the app?

**Comment by nekohasekai** [comment]
This is to prevent users with no android experience from compiling Release (usually via actions). To compile Release, first configure your own signature.
