### ISSUE TITLE
a route rule with a mix of IP and Domain won't work

### ISSUE THREAD

**Issue by samlux04** [SagerNet/SagerNet#497]
The route rules with only IP or domain works but putting them together in one rule won't. I'd like to put them together for convenience. I hope it will work in the future. Thanks.
Pic related.

This won't work 
![Screenshot_20220703-024651_SagerNet](https://user-images.githubusercontent.com/85811479/177013076-28b0028b-70a6-4f96-b818-5128c82e3663.png)

This works
![IMG_20220703_025704](https://user-images.githubusercontent.com/85811479/177013127-c2e42790-f148-4ae6-a5f3-220ec47e8465.jpg)

**Comment by nekohasekai** [comment]
They are AND logic.
