### ISSUE TITLE
[BUG] TUIC-Plugin 远程dns设置为udp://8.8.8.8时无法访问网页

### ISSUE THREAD

**Issue by Fhokud** [SagerNet/SagerNet#501]
新增的Redoce RTT 值无论写false还是true，保存退出后重新进入就会变成未设置

建议像Disable SNI 一样做成选项
选项名就叫 

> en：Enable 0-RTT QUIC handshake
zh：启用QUIC 0-RTT握手

**Comment by Fhokud** [comment]
补充（BUG)
当远程dns设置为udp://8.8.8.8时无网络
将远程dns设置改成tcp://8.8.8.8时正常

**Comment by Fhokud** [comment]
感谢修复
https://github.com/SagerNet/SagerNet/releases/tag/0.8.1-rc02

**Comment by Fhokud** [comment]
https://github.com/SagerNet/SagerNet/issues/501#issuecomment-1176246441 
此问题任未解决

使用工具中nat行为发现可以测出结果（tcp://8.8.8.8）
（udp://8.8.8.8）测试则失败，且无网络

**Comment by Fhokud** [comment]
可以正常访问网页 日志
I/v2ray-core: transport/internet/tcp: listening TCP on 127.0.0.1:3079
I/v2ray-core: transport/internet/udp: listening UDP on 127.0.0.1:3079
I/v2ray-core: transport/internet/tcp: listening TCP on 127.0.0.1:4681
I/v2ray-core: transport/internet/tcp: listening TCP on 127.0.0.1:40765
I/v2ray-core: transport/internet/udp: listening UDP on 127.0.0.1:40765
I/v2ray-core: transport/internet/tcp: listening TCP on 127.0.0.1:6451
I/v2ray-core: transport/internet/udp: listening UDP on 127.0.0.1:6451
W/v2ray-core: V2Ray 5.0.16 started
E/libtuic : [2022-07-07T02:18:23Z INFO ] [socks5] Started. Listening: 127.0.0.1:38411
E/libtuic : [2022-07-07T02:18:23Z INFO ] [relay] Started. Target server: 127.0.0.1:40765 (服务器域名)
I/v2ray-core: app/dispatcher: taking detour [dns-out] for [udp:1.0.0.1:53]
I/v2ray-core: proxy/dns: handling DNS traffic to tcp:8.8.8.8:53
I/v2ray-core: app/dispatcher: taking detour [dns-out] for [udp:1.0.0.1:53]
I/v2ray-core: proxy/dns: handling DNS traffic to tcp:8.8.8.8:53
D/v2ray-core: app/dns: domain www.google.com will use DNS in order: [TCP//8.8.8.8]
D/v2ray-core: app/dns: domain www.google.com will use DNS in order: [TCP//8.8.8.8]
I/v2ray-core: app/dns: establishing new connection for tcp:8.8.8.8:53
W/v2ray-core: app/dispatcher: default route for tcp:8.8.8.8:53
I/v2ray-core: transport/internet/tcp: dialing TCP to tcp:127.0.0.1:38411
E/libtuic : [2022-07-07T02:18:23Z DEBUG] [socks5] [127.0.0.1:45592] [establish]
E/libtuic : [2022-07-07T02:18:23Z INFO ] [socks5] [127.0.0.1:45592] [connect] [8.8.8.8:53]
E/libtuic : [2022-07-07T02:18:23Z INFO ] [relay] [task] [connect] [8.8.8.8:53]
E/libtuic : [2022-07-07T02:18:23Z WARN ] [relay] [connection] Unable to convert the connection into 0-RTT
D/v2ray-core: [1172606756] proxy/dokodemo: processing connection from: 127.0.0.1:38222
I/v2ray-core: [1172606756] proxy/dokodemo: received request for 127.0.0.1:38222
I/v2ray-core: [1172606756] app/dispatcher: taking detour [direct] for [udp:服务器域名:443]
D/v2ray-core: app/dns: domain 服务器域名 matches following rules: [[full:服务器域名](DNS idx:1)]
D/v2ray-core: app/dns: domain 服务器域名 will use DNS in order: [localhost]
D/v2ray-core: 127.0.0.1:38222 accepted udp:服务器域名:443 [direct]
D/v2ray-core: [1172606756] app/dns: localhost got answer: 服务器域名 -> TypeA [服务器IP]
I/v2ray-core: [1172606756] proxy/freedom: opening connection to udp:服务器IP:443
I/v2ray-core: [1515307515] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
E/libtuic : [2022-07-07T02:18:24Z DEBUG] [relay] [connection] [establish]
E/libtuic : [2022-07-07T02:18:24Z DEBUG] [relay] [connection] [heartbeat]
E/libtuic : [2022-07-07T02:18:24Z DEBUG] [relay] [connection] [authentication]
E/libtuic : [2022-07-07T02:18:24Z DEBUG] [relay] [task] [connect] [8.8.8.8:53] [success]
D/v2ray-core: app/dns: TCP//8.8.8.8 got answer: www.google.com -> TypeAAAA [2607:f8b0:4005:80e::2004]
D/v2ray-core: app/dns: TCP//8.8.8.8 got answer: www.google.com -> TypeA [142.250.189.228]
D/v2ray-core: app/dispatcher: dispatch link to tcp:www.google.com:80
W/v2ray-core: app/dispatcher: default route for tcp:www.google.com:80
D/v2ray-core: app/dns: dns cache HIT www.google.com -> [142.250.189.228]
I/v2ray-core: transport/internet/tcp: dialing TCP to tcp:127.0.0.1:38411
E/libtuic : [2022-07-07T02:18:25Z DEBUG] [socks5] [127.0.0.1:45598] [establish]
E/libtuic : [2022-07-07T02:18:25Z INFO ] [socks5] [127.0.0.1:45598] [connect] [142.250.189.228:80]
E/libtuic : [2022-07-07T02:18:25Z INFO ] [relay] [task] [connect] [142.250.189.228:80]
E/libtuic : [2022-07-07T02:18:25Z DEBUG] [relay] [task] [connect] [142.250.189.228:80] [success]
I/v2ray-core: app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context deadline exceeded
E/libtuic : [2022-07-07T02:18:28Z WARN ] [socks5] [127.0.0.1:45598] Connection reset by peer (os error 104)
E/libtuic : [2022-07-07T02:18:28Z DEBUG] [socks5] [127.0.0.1:45592] [disconnect]
I/v2ray-core: [2616214314] proxy/socks: TCP Connect request to tcp:alive.github.com:443
D/v2ray-core: app/dispatcher: dispatch conn to tcp:alive.github.com:443
I/v2ray-core: [2616214314] app/dispatcher: sniffed domain: alive.github.com
W/v2ray-core: [2616214314] app/dispatcher: default route for tcp:alive.github.com:443
D/v2ray-core: tcp:127.0.0.1:46996 accepted tcp:alive.github.com:443 [proxy-global-192]
D/v2ray-core: app/dns: domain alive.github.com will use DNS in order: [TCP//8.8.8.8]
I/v2ray-core: app/dns: establishing new connection for tcp:8.8.8.8:53
W/v2ray-core: app/dispatcher: default route for tcp:8.8.8.8:53
I/v2ray-core: transport/internet/tcp: dialing TCP to tcp:127.0.0.1:38411
E/libtuic : [2022-07-07T02:18:34Z DEBUG] [socks5] [127.0.0.1:45618] [establish]
E/libtuic : [2022-07-07T02:18:34Z INFO ] [socks5] [127.0.0.1:45618] [connect] [8.8.8.8:53]
E/libtuic : [2022-07-07T02:18:34Z INFO ] [relay] [task] [connect] [8.8.8.8:53]
E/libtuic : [2022-07-07T02:18:34Z DEBUG] [relay] [task] [connect] [8.8.8.8:53] [success]
D/v2ray-core: [2616214314] app/dns: TCP//8.8.8.8 got answer: alive.github.com -> TypeA [140.82.113.25]
I/v2ray-core: [2616214314] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:38411
E/libtuic : [2022-07-07T02:18:35Z DEBUG] [socks5] [127.0.0.1:45622] [establish]
E/libtuic : [2022-07-07T02:18:35Z INFO ] [socks5] [127.0.0.1:45622] [connect] [140.82.113.25:443]
E/libtuic : [2022-07-07T02:18:35Z INFO ] [relay] [task] [connect] [140.82.113.25:443]
E/libtuic : [2022-07-07T02:18:35Z DEBUG] [relay] [task] [connect] [140.82.113.25:443] [success]

**Comment by Fhokud** [comment]
不能访问网页 -日志
E/libtuic : [2022-07-07T02:17:46Z INFO ] [relay] Started. Target server: 127.0.0.1:40037 (服务器域名)
E/libtuic : [2022-07-07T02:17:46Z INFO ] [socks5] Started. Listening: 127.0.0.1:38415
I/v2ray-core: app/dispatcher: taking detour [dns-out] for [udp:1.0.0.1:53]
I/v2ray-core: proxy/dns: handling DNS traffic to udp:8.8.8.8:53
I/v2ray-core: app/dispatcher: taking detour [dns-out] for [udp:1.0.0.1:53]
I/v2ray-core: proxy/dns: handling DNS traffic to udp:8.8.8.8:53
D/v2ray-core: app/dns: domain www.google.com will use DNS in order: [UDP//8.8.8.8]
D/v2ray-core: app/dns: domain www.google.com will use DNS in order: [UDP//8.8.8.8]
I/v2ray-core: app/dns: establishing new connection for udp:8.8.8.8:53
W/v2ray-core: app/dispatcher: default route for udp:8.8.8.8:53
I/v2ray-core: transport/internet/tcp: dialing TCP to tcp:127.0.0.1:38415
E/libtuic : [2022-07-07T02:17:46Z DEBUG] [socks5] [127.0.0.1:45958] [establish]
E/libtuic : [2022-07-07T02:17:46Z INFO ] [socks5] [127.0.0.1:45958] [associate] [8.8.8.8:53]
E/libtuic : [2022-07-07T02:17:46Z INFO ] [relay] [task] [associate] [3888633003]
E/libtuic : [2022-07-07T02:17:46Z DEBUG] [socks5] [127.0.0.1:45958] [associate] [packet-to] 8.8.8.8:53
E/libtuic : [2022-07-07T02:17:46Z WARN ] [relay] [connection] Unable to convert the connection into 0-RTT
E/libtuic : [2022-07-07T02:17:46Z DEBUG] [socks5] [127.0.0.1:45958] [associate] [packet-to] 8.8.8.8:53
D/v2ray-core: [1515307515] proxy/dokodemo: processing connection from: 127.0.0.1:41010
I/v2ray-core: [1515307515] proxy/dokodemo: received request for 127.0.0.1:41010
I/v2ray-core: [1515307515] app/dispatcher: taking detour [direct] for [udp:服务器域名:443]
D/v2ray-core: app/dns: domain 服务器域名 matches following rules: [[full:服务器域名](DNS idx:1)]
D/v2ray-core: app/dns: domain 服务器域名 will use DNS in order: [localhost]
D/v2ray-core: 127.0.0.1:41010 accepted udp:服务器域名:443 [direct]
D/v2ray-core: [1515307515] app/dns: localhost got answer: 服务器域名 -> TypeAAAA [服务器IP]
I/v2ray-core: [1515307515] proxy/freedom: opening connection to udp:服务器IP:443
I/v2ray-core: [3092330084] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [relay] [connection] [establish]
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [relay] [task] [associate] [3888633003] [send] [8.8.8.8:53] [success]
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [relay] [connection] [authentication]
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [relay] [connection] [heartbeat]
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [relay] [task] [associate] [3888633003] [send] [8.8.8.8:53] [success]
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [relay] [task] [associate] [3888633003] [recv] [[::ffff:8.8.8.8]:53] [success]
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [socks5] [127.0.0.1:45958] [associate] [packet-from] [::ffff:8.8.8.8]:53
D/v2ray-core: app/dns: no callback for response 0
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [relay] [task] [associate] [3888633003] [recv] [[::ffff:8.8.8.8]:53] [success]
E/libtuic : [2022-07-07T02:17:47Z DEBUG] [socks5] [127.0.0.1:45958] [associate] [packet-from] [::ffff:8.8.8.8]:53
D/v2ray-core: app/dns: UDP//8.8.8.8 got answer: www.google.com -> TypeAAAA [2607:f8b0:4005:80e::2004]
I/v2ray-core: app/dispatcher: taking detour [dns-out] for [udp:1.0.0.1:53]
I/v2ray-core: proxy/dns: handling DNS traffic to udp:8.8.8.8:53
I/v2ray-core: proxy/dns: ip query > context canceled
I/v2ray-core: app/dispatcher: taking detour [dns-out] for [udp:1.0.0.1:53]
I/v2ray-core: proxy/dns: handling DNS traffic to udp:8.8.8.8:53
I/v2ray-core: app/dispatcher: taking detour [dns-out] for [udp:1.0.0.1:53]
I/v2ray-core: proxy/dns: handling DNS traffic to udp:8.8.8.8:53
I/v2ray-core: [3357868378] proxy/socks: TCP Connect request to tcp:alive.github.com:443
D/v2ray-core: app/dispatcher: dispatch conn to tcp:alive.github.com:443
I/v2ray-core: [3357868378] app/dispatcher: sniffed domain: alive.github.com
D/v2ray-core: tcp:127.0.0.1:46908 accepted tcp:alive.github.com:443 [proxy-global-192]
W/v2ray-core: [3357868378] app/dispatcher: default route for tcp:alive.github.com:443
D/v2ray-core: app/dns: domain alive.github.com will use DNS in order: [UDP//8.8.8.8]
E/libtuic : [2022-07-07T02:17:56Z DEBUG] [socks5] [127.0.0.1:45958] [associate] [packet-to] 8.8.8.8:53
E/libtuic : [2022-07-07T02:17:56Z DEBUG] [relay] [task] [associate] [3888633003] [send] [8.8.8.8:53] [success]
E/libtuic : [2022-07-07T02:17:56Z DEBUG] [relay] [task] [associate] [3888633003] [recv] [[::ffff:8.8.8.8]:53] [success]
E/libtuic : [2022-07-07T02:17:56Z DEBUG] [socks5] [127.0.0.1:45958] [associate] [packet-from] [::ffff:8.8.8.8]:53
D/v2ray-core: app/dns: no callback for response 0
E/libtuic : [2022-07-07T02:17:57Z DEBUG] [relay] [connection] [heartbeat]
E/libtuic : [2022-07-07T02:18:01Z DEBUG] [socks5] [127.0.0.1:45998] [establish]
I/v2ray-core: [3357868378] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:38415
E/libtuic : [2022-07-07T02:18:01Z INFO ] [socks5] [127.0.0.1:45998] [connect] [alive.github.com:443]
E/libtuic : [2022-07-07T02:18:01Z INFO ] [relay] [task] [connect] [alive.github.com:443]
E/libtuic : [2022-07-07T02:18:01Z DEBUG] [relay] [task] [connect] [alive.github.com:443] [success]
E/libtuic : [2022-07-07T02:18:03Z DEBUG] [socks5] [127.0.0.1:45998] [disconnect

**Comment by Fhokud** [comment]
https://github.com/EAimTY/tuic/issues/60
确定了，是TUIC的BUG

**Comment by nekohasekai** [comment]
不建议使用 UDP DNS。

**Comment by Fhokud** [comment]
已修复
