### ISSUE TITLE
关于插件节点的流量处理逻辑

### ISSUE THREAD

**Issue by Fhokud** [SagerNet/SagerNet#508]
我查看了sagernet插件节点的配置文件
 
 

> {
      "listen": "127.0.0.1",
      "port": 54676,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "TUIC服务器IP",
        "network": "tcp,udp",
        "port": 443
      },
      "tag": "proxy-mapping"
    }

> {
    "relay": {
        "server": "mirror-us2.foolyou.top",
        "alpn": [
            "h3"
        ],
        **"ip": "127.0.0.1",**
        "token": "密码",
        "port": 34949,
        "udp_relay_mode": "quic",
        "reduce_rtt": true,
        "disable_sni": false,
        "max_udp_relay_packet_size": 1500,
        "congestion_controller": "bbr"
    },
    "log_level": "debug",
    "local": {
        "ip": "127.0.0.1",
        "port": 54676
    }
}

这些配置文件的流量处理逻辑是

- 流量 （socks/http）=> core（socks）=> TUIC （quic）=> core（dokodemo-door）=> 服务器

我十分不明白为什么要多此一举把插件的流量指定到127.0.0.1再通过dokodemo-door转发走？

**Comment by Fhokud** [comment]
hysteria、naiverproxy、Trojan-go都存在此问题

**Comment by Fhokud** [comment]
可以告诉我愿意吗，谢谢。

**Comment by Fhokud** [comment]
为了让core处理DNS请求？

**Comment by nekohasekai** [comment]
https://developer.android.com/reference/android/net/VpnService#protect(int)

**Comment by Fhokud** [comment]
明白了，谢谢。
