### ISSUE TITLE
workflows  not working

### ISSUE THREAD

**Issue by muzaffer72** [SagerNet/SagerNet#512]
### Discussed in https://github.com/SagerNet/SagerNet/discussions/511

<div type='discussions-op-text'>

<sup>Originally posted by **muzaffer72** August  4, 2022</sup>
I have build error. I used github workflows. Whats problem.

![resim](https://user-images.githubusercontent.com/10040551/182714810-41cf5ffb-4e32-487f-b14e-31e3fa48b7a1.png)
</div>

**Comment by nekohasekai** [comment]
Read the source code.

**Comment by muzaffer72** [comment]
![resim](https://user-images.githubusercontent.com/10040551/182859369-c65df495-b2f1-4415-8d68-372d4c79633d.png)
