### ISSUE TITLE
请求更新 TUIC 0.8.5 和 0.8.4版本 插件

### ISSUE THREAD

**Issue by chika0801** [SagerNet/SagerNet#522]
https://github.com/EAimTY/tuic/releases

请问是否有这2个版本的更新计划？

**Comment by enfein** [comment]
@chika0801 你需要 0.8.4 和 0.8.5，还是只需要最新的 0.8.5？

**Comment by chika0801** [comment]
> @chika0801 你需要 0.8.4 和 0.8.5，还是只需要最新的 0.8.5？

2个版本号都要。0.8.4是的更新日志是  IPv4 stack UDP sockets as UDP outbound 0.8.5是IPv6

**Comment by chika0801** [comment]
十分感谢
