### ISSUE TITLE
关于编写插件的问题

### ISSUE THREAD

**Issue by iceBear67** [SagerNet/SagerNet#523]
~~可能有点弱智，因为我对android开发不是很熟悉~~

想给 SN 加 sosistab (geph-official/geph) 支持，然后去参照了一下其他插件的实现，发现都是引用一些 `.so` 文件，所以有一些疑问

这些 .so 是如何编译出来的？像是 pingtunnel 似乎也没有直接提供 libpt 这种文件（或者我没看到。。）

**Comment by nilxbit** [comment]
作者曾在某个issue里说，那些.so是可执行文件，安卓打包时有些限制，比如naive可执行文件，重命名为libnaive.so再打包

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/SagerNet/tree/dev/bin/plugin

**Comment by iceBear67** [comment]
非常感谢，我一会看看魔数检验一下
