### ISSUE TITLE
hysteria服务端更新到最新的1.21后不能用了

### ISSUE THREAD

**Issue by znlsl** [SagerNet/SagerNet#528]
反馈个问题哈，hysteria服务端更新到最新的1.21后不能用了，需要的话我提供个log哈。

**Comment by zhutailin** [comment]
换成UDP可以，hysteria1.21用wechat-video需要版本客户端和服务端版本一样

**Comment by nekohasekai** [comment]
wechat-video 基本上是自欺欺人，没有更新的意义。

**Comment by enfein** [comment]
This is a problem of server side, not relevant to the plugin.
