### ISSUE TITLE
安卓使用trojan-go插件提示未知插件

### ISSUE THREAD

**Issue by qiuzi** [SagerNet/SagerNet#53]
安装正常 连接时提示未知插件

**Comment by nekohasekai** [comment]
检查插件和SN的厂商自定义权限 (像自启动、唤醒...等)

**Comment by zyp997** [comment]
@qiuzi  解决了吗？

**Comment by qiuzi** [comment]
@zyp997 按照 nekoh说的方法解决了

**Comment by IsQiao** [comment]
> 检查插件和SN的厂商自定义权限 (像自启动、唤醒...等)

解决了 感谢大佬

**Comment by slarkcoder** [comment]
> 检查插件和SN的厂商自定义权限 (像自启动、唤醒...等)

MIUI，已安装 Naive 插件，启动时提示“缺少插件”，这个办法也有用！
