### ISSUE TITLE
[regression] `libhysteria exists too fast (exit code: 1)` - Hysteria plug-in 1.2.1

### ISSUE THREAD

**Issue by enihcam** [SagerNet/SagerNet#533]
**Before submitting an issue, please make sure you are using the latest version of SagerNet.**

### Describe the bug

After upgraded Hysteria plug-in to 1.2.1, connection cannot be established.
![84e550dc65855ab79fce9ee1017e286](https://user-images.githubusercontent.com/7010097/192437878-5bffc6e4-4b1a-4ff9-a59f-dda2087a8beb.jpg)

### Debug Information

> About -> Export Debug Information

**If you do not send the file directly, please use the Markdown code block format, otherwise your
issue will be closed!**

```
Please make sure that you have turned on the "Enable Log" setting before reproducing. 

If your exported logs are too small, please go to Developer Settings to increase the log buffer and
reboot the device to reproduce and send the logs again.
```

### Smartphone (please complete the following information)

- Kernel version: [e.g. 4.19.114]
- Device: [e.g. MI6]
- OS: [e.g. Android8.1]

**Comment by vagreargnatry** [comment]
我的日志说 invalid syntax: failed to set resolver 可能于此有关：

**Comment by nekohasekai** [comment]
@enfein 下次更新之前测试下吧hhh

**Comment by enfein** [comment]
好的，之后尽量本地构建再用 workflow。

另外修复这个问题是不是需要一个新的 SagerNet 版本才行？

**Comment by nekohasekai** [comment]
> 好的，之后尽量本地构建再用 workflow。
> 
> 另外修复这个问题是不是需要一个新的 SagerNet 版本才行？

（可以 fork patch 他的参数（（

**Comment by enihcam** [comment]
redownloaded and tried but still the same error.

**Comment by willaytoun** [comment]
遇到同样的问题

**Comment by trulyliu** [comment]
Same issue

**Comment by mmm8955405** [comment]
同样问题

**Comment by enfein** [comment]
Added a warning in the release page. Plan to provide a debug build for validation before releasing a new SagerNet version.

**Comment by enfein** [comment]
@enihcam @willaytoun @trulyliu @mmm8955405

Can you try install SagerNet APK from https://github.com/SagerNet/SagerNet/actions/runs/3349188592 and see if the issue is fixed?

Thank you

**Comment by trulyliu** [comment]
@enfein this new build works well with hysteria-plugin-1.2.1

**Comment by mmm8955405** [comment]
> @enihcam @willaytoun @trulyliu @mmm8955405
> 
> [您可以尝试从https://github.com/SagerNet/SagerNet/actions/runs/3349188592](https://github.com/SagerNet/SagerNet/actions/runs/3349188592)安装 SagerNet APK并查看问题是否已解决？
> 
> 谢谢

连接的这个版本，配合hysteria-plugin-1.2.1-arm64-v8a.apk使用，显示可以连接成功，但是没有成功代理

**Comment by Billyas** [comment]
[this version may be help](https://github.com/SagerNet/SagerNet/releases/download/hysteria-plugin-1.1.0/hysteria-plugin-1.1.0-arm64-v8a.apk)
it useful to me

**Comment by enfein** [comment]
@mmm8955405 在我这里 SagerNet debug build 和 hysteria 1.2.1 插件配合是可以正常使用的。我会发布一个新的 SagerNet 版本来兼容 1.2.1 插件。如果今后还有问题我们可以继续讨论。

**Comment by enfein** [comment]
Please upgrade to SagerNet 0.8.1-rc03 if you want to use hysteria plugin 1.2.1.

**Comment by italy2010** [comment]
using  hysteriaplugin v 1.3.0  and sagernet 0.8.1 rc 02 i have libhysteria exists too fast (exit code: 1) error

**Comment by zhyonc** [comment]
> using hysteriaplugin v 1.3.0 and sagernet 0.8.1 rc 02 i have libhysteria exists too fast (exit code: 1) error

Use [0.8.1-rc03](https://github.com/SagerNet/SagerNet/releases/tag/0.8.1-rc03)  can solver this error

**Comment by italy2010** [comment]
> 

i tested still same error.
hysteria v 1.3.0
sagernet 0.8.1 rc03

**Comment by Swingx77** [comment]
> > 
> 
> i tested still same error. hysteria v 1.3.0 sagernet 0.8.1 rc03

I met the same problem and I had a try on:

- make sure the Insecure Option in On - or the URL Insecure  value is 1.
- have a try on hysteria plugin v1.2.1; while SagerNet keeps the latest version.

it works.

**Comment by Swingx77** [comment]
hysteria-plugin-1.3.2-arm64-v8a.apk works also fine.
So the only cause of "libhysteria exists too fast (exit code: 1)" is Insecure option - Off.

**Comment by Swingx77** [comment]
hysteria-plugin-1.3.2-arm64-v8a.apk works also fine.

So the only cause of "libhysteria exists too fast (exit code: 1)" on my Pixel phone is the Insecure option - Off.
Insecure is a setting created by the Hi_Hysteria installing "bash <(curl -fsSL https://git.io/hysteria.sh)", and should be kept as its default value (On).

**Comment by zerofo** [comment]
> 我的日志说 invalid syntax: failed to set resolver 可能与此有关： [apernet/hysteria#440](https://github.com/apernet/hysteria/issues/440) https://github.com/SagerNet/SagerNet/blob/dev/app/src/main/java/io/nekohasekai/sagernet/fmt/hysteria/HysteriaFmt.kt#L191

0.8.1-rc03 + hysteria plugin 1.3.5 一样的报错。。 有解吗？
