### ISSUE TITLE
能否增加 shadow-tls 插件

### ISSUE THREAD

**Issue by loveqianool** [SagerNet/SagerNet#542]
https://github.com/ihciah/shadow-tls

**Comment by longmoon77** [comment]
亲爱的loveqianool，您好。

您描述的问题可能需要sing-box在Android上的图形实现，目前Sagernet使用的是经Project S修改的v2ray-core，您可以期待未来可能有sing-box在Android上的图形界面客户端。

感谢您对Project S的支持。

Best Regards,
longmoon77

**Comment by samho1234567** [comment]
sagernet 也可以直接安装使用 shadowsocks SIP003 ShadowTLS plugin，不过 shadowsocks 只可以 AEAD 加密 （chacha20-ietf-poly1305、xchacha20-ietf-poly1305、aes-128-gcm、aes-192-gcm、aes-256-gcm） 和非 AEAD 加密，不能使用 Shadowsocks-2022 协议，希望将来 sagernet 可以支持。

https://github.com/maskedeken/shadow-tls-android/releases

来源：https://github.com/ihciah/shadow-tls/issues/25
