### ISSUE TITLE
非443端口连接naive服务失败

### ISSUE THREAD

**Issue by sunlewuyou** [SagerNet/SagerNet#544]
部分错误日志如下:
E/libnaive: WARNING: linker: Warning: "/data/app/~~tq9dWpPxTNUuzGY-O8j4Hg==/io.nekohasekai.sagernet.plugin.naive-ml5gjBlrnl2a3efEmfzBdw==/lib/arm64/libnaive.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
E/libnaive: [1006/150308.266142:ERROR:cert_issuer_source_aia.cc(135)] AiaRequest::OnFetchCompleted got error -7
E/libnaive: [1006/150308.266942:ERROR:cert_verify_proc_builtin.cc(700)] CertVerifyProcBuiltin for mydemo.ml failed:
E/libnaive: ----- Certificate i=0 (CN=mydemo.ml) -----
E/libnaive: ERROR: No matching issuer found

同样的配置在AnXray上运行正常！

**Comment by enfein** [comment]
443 端口连接可以么？

```
E/libnaive: ERROR: No matching issuer found
```

这应该不是根本原因。请提供 SagerNet 和 naive 版本号以及详细的日志信息。

**Comment by sunlewuyou** [comment]
@enfein 仔细对比AnXray，发现TUN实现切换到gVisor才可以，默认是system。不知道为什么默认是system？难道默认不应该是最合适的配置才对吗？

**Comment by klzgrad** [comment]
AiaRequest::OnFetchCompleted got error -7

-7是timeout的意思。这里的情况是如果证书信任链上有intermediary issuer而且这个issuer没有在系统的证书库里面，aia会去通过网络下载这个证书。如果下载失败，就无法完成服务器证书认证。这里下载失败可以是环境网络原因，也要考虑这个下载的连接是否被vpn错误配置给挡住了，这个连接不能走vpn。
