### ISSUE TITLE
hysteria-plugin-1.2.1 无法使用

### ISSUE THREAD

**Issue by chika0801** [SagerNet/SagerNet#549]
https://github.com/SagerNet/SagerNet/releases/tag/hysteria-plugin-1.2.1

使用时，提示此信息，换到1.1版本正常启动使用，安装版本是 arm64-v8a.apk

![Screenshot_2022-10-10-17-31-41-876_io nekohasekai sagernet-edit](https://user-images.githubusercontent.com/88967758/194837247-74119d0e-48d1-46fb-867a-c6ff82ac9870.jpg)

**Comment by vagreargnatry** [comment]
https://github.com/SagerNet/SagerNet/issues/533
https://github.com/SagerNet/SagerNet/commit/b9d23a22438fbea2b268fd5e5a0e8b595ea5e85b
我想应该是修好了，等待 SagerNet 发下一个版本就好了。
