### ISSUE TITLE
关于默认测试链接安全性的疑问

### ISSUE THREAD

**Issue by PufferBlue** [SagerNet/SagerNet#555]
开发者您好，我注意到SagerNet目前的默认测试链接为`https://api.v2fly.org/checkConnection.svgz` 

首先，我对这个默认测试链接的选择表示疑惑，为什么会选择这样一个测试链接？我并没有在其它地方的文档找到关于这个链接的记载

其次，我对选择这个测试链接带来的安全问题表示担忧，如果第三方可以控制该域名，或者可以监听到这个域名的通信流量，甚至只需要监听到DNS请求流量，则所有节点的落地IP都将被暴露

在此我建议将默认测试链接改为`https://www.google.com/generate_204`，首先`www.google.com`没有独特的域名特征，不会暴露节点流量，而且测试访问Google可以更准确的反馈网络延迟

**Comment by GleenJi** [comment]
好像这个链接以前能用，后来不能用了，xray默认是谷歌的204
