### ISSUE TITLE
Missing Plugin

### ISSUE THREAD

**Issue by lumiseven** [SagerNet/SagerNet#556]
[**Version**]
> Version: 0.8.1-rc02
> Version(SagerNet/v2ray-core): v5.0.16
> Version(naive-plugin): v105.0.5195.52-1

[**Problem**]
> Profile ** requires the Naive plugin, but your propriety equipment vendor (usually surveillance capital giants and malware maker) tempted with your android, making the plugin unusable.

**Comment by Mandi-Sa** [comment]
See https://sagernet.org/plugin/

**Comment by lumiseven** [comment]
naive-plugin(v105.0.5195.52-1) which download from f-droid will raise this problem in some case, and direct download from release page is not.
