### ISSUE TITLE
null cannot be cast to non-null type kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any?>>

### ISSUE THREAD

**Issue by shugo-chara** [SagerNet/SagerNet#57]
导入clash里的订阅规则后出现如图提示，添加失败。
订阅地址格式：https://xxxx.com/xxx/xxxx.yaml
里面包含proxy-groups，rule-providers和proxy-providers的更新地址等。
![IMG_20210502_214643](https://user-images.githubusercontent.com/20610965/116813676-e70d1780-ab8f-11eb-8818-317d9c35fe68.jpg)

**Comment by arhahmad** [comment]
Thank you for your good program, please design a dark theme, pink color annoys the eyes, ugly logo and it is better to reconsider, the option to delete all servers should also be designed, I wish the internet usage part was under the server, Thankful

**Comment by nekohasekai** [comment]
暂未支持 proxy-providers

**Comment by shugo-chara** [comment]
@nekohasekai 手动把proxies里的服务器地址（ss）添加后可以正常连接。测速有点慢但连接正常，但是实际不生效也是因为支持不全的原因吗，没有规则列表。
