### ISSUE TITLE
naiveproxy更新请求

### ISSUE THREAD

**Issue by Lelianna** [SagerNet/SagerNet#587]
naiveproxy已经更新到108了，是否可以更新一下naiveproxy的plugin。

**Comment by Bryan2333** [comment]
见 https://github.com/SagerNet/SagerNet/pull/588

**Comment by enfein** [comment]
需要更新 build script...

**Comment by zedifen** [comment]
> 需要更新 build script...

我看了一下 https://github.com/SagerNet/SagerNet/actions/runs/3699283056 这次 Action Run 的日志, 感觉错误的原因很奇怪, 怀疑是 Runner 机器抽风, 要不要试试重新触发一次 Release Workflow ?

**Comment by enfein** [comment]
@zedifen 失败了两次，在同一个地方

**Comment by Yewip** [comment]
原Workflow编译失败，都是在执行dirname输出路径时提示参数报错。由于我只需要arm64 v8a版本，所以直接把这行去掉了`APK=$(dirname $APK)`，随后Build成功

**Comment by zedifen** [comment]
@enfein 用 SSH 连到 Runner 上, 终于找到错误原因了 ....

PR #588 修改版本号的时候 [多了个空格](https://github.com/SagerNet/SagerNet/commit/a75d8f283b77eab0933d846bc44d0b65c4be8e87#diff-6f53b611fb83c29345a406e541f67ffbf34aa448377b0e7a749b2fb4e04ac362R5), 于是 Gradle 构建完成之后输出的文件名之间有空格; find 命令的输出就如下

```console
runner@fv-az206-25:~/work/SagerNet/SagerNet$ find plugin/naive/build/outputs/apk -name '*arm64-v8a*.apk'
plugin/naive/build/outputs/apk/oss/release/naive-plugin-108.0.5359.94-1 -arm64-v8a.apk
```

由于 dirname 后边没加引号 ([src](https://github.com/SagerNet/SagerNet/blob/dev/.github/workflows/release_naive.yml#L120)), 所以相当于执行 `dirname ... -arm64-v8a.apk`, 就被当成有个 `-a` 参数了 (于是就是 'invalid option' 的报错信息)

**Comment by enfein** [comment]
@zedifen Thank you for your contribution!
