### ISSUE TITLE
[Feature request] 允许隐藏默认组

### ISSUE THREAD

**Issue by realSakaro** [SagerNet/SagerNet#60]
**Is your feature request related to a problem? Please describe.**
由于个人基本使用订阅，不会手动导入节点，所以想删除默认组
但发现默认组无法隐藏或删除

**Describe the solution you'd like**
在默认组编辑名称界面增加隐藏按钮

**Describe alternatives you've considered**
暂无

**Additional context**
暂无

**Comment by imldy** [comment]
也可以考虑记住APP关闭时处于显示状态的组，下次启动时自动切换。
