### ISSUE TITLE
Feature request: Hysteria Port Hopping

### ISSUE THREAD

**Issue by msshn** [SagerNet/SagerNet#606]
Hysteria introduced port hopping in v1.30 which is a really useful feature. Please consider supporting it in future updates of hysteria plugin.

**Comment by Nullizer** [comment]
+1

**Comment by wangxiaoerYah** [comment]
yes,need this. +1

**Comment by RayWangQvQ** [comment]
+1

**Comment by tpunix** [comment]
现在已经有1.3.2版本了。但端口那一栏，并不能设置范围端口。此栏只支持数字输入。

**Comment by mrzeuscn** [comment]
希望更新支持下这个功能
