### ISSUE TITLE
编译的时候出现这种问题 求解决方案?

### ISSUE THREAD

**Issue by alsojin0806** [SagerNet/SagerNet#61]
No signature of method: build_dwpmq0xqf7xu6cu3cyp9012g3.android() is applicable for argument types: (build_dwpmq0xqf7xu6cu3cyp9012g3$_run_closure2) values: [build_dwpmq0xqf7xu6cu3cyp9012g3$_run_closure2@26bfc8a7]
Open File

**Comment by nekohasekai** [comment]
参考 GitHub Action 的编译流程。
