### ISSUE TITLE
尊敬的SagerNet开发者您好，希望SagerNet能加入对XTLS-RPRX-VISION流控的支持。

### ISSUE THREAD

**Issue by ColanCN** [SagerNet/SagerNet#614]
RT，随着Project X团队带来了VLESS协议的全新流控XTLS-RPRX-VISION，XTLS的很多历史性问题也获得了解决，我也希望SagerNet开发者团队能给SagerNet带来XTLS-RPRX-VISION流控的全新支持！

也再次感谢SagerNet的开发者这么久以来的默默付出。

**Comment by cnclg** [comment]
若能跟进新流控的支持，的确是一个好消息，感谢SagerNet开发团队

**Comment by ColanCN** [comment]
> 若能跟进新流控的支持，的确是一个好消息，感谢SagerNet开发团队

SagerNet这个项目不会被放弃了吧？
