### ISSUE TITLE
插件是不是不能装在 爱国为 手机里？

### ISSUE THREAD

**Issue by ironmantonystark** [SagerNet/SagerNet#649]
爱国为 mate 10 pro 是32位 CPU ,能转Sagerent32位版本和 mieru 32位插件，但装完不能连mieru ，说没有 mieru  插件，明明装了，是手机把功能阉割了还是什么原因？

**Comment by ironmantonystark** [comment]
真的不行，关闭此贴

**Comment by zedifen** [comment]
可能是智能手机操作系统对安卓进行了某些修改，导致无法识别。参考这处尚未包含在发行版中的中文翻译改动：

https://github.com/SagerNet/SagerNet/commit/60c9544515fd4d09c217e004b3abedb31a01bd83#diff-d9c30b0c0a46ff73de30b4ec09e9219f1edad9a9ce584661d8170e5545d6aa50R369

**Comment by ironmantonystark** [comment]
> 可能是智能手机操作系统对安卓进行了某些修改，导致无法识别。参考这处尚未包含在发行版中的中文翻译改动：
> 
> [60c9544#diff-d9c30b0c0a46ff73de30b4ec09e9219f1edad9a9ce584661d8170e5545d6aa50R369](https://github.com/SagerNet/SagerNet/commit/60c9544515fd4d09c217e004b3abedb31a01bd83#diff-d9c30b0c0a46ff73de30b4ec09e9219f1edad9a9ce584661d8170e5545d6aa50R369)

我把手机刷成国际版没有那个出错提示了，但是连不上去，经常time out
