### ISSUE TITLE
[Feature request] 增加隐藏后台和开机自启动

### ISSUE THREAD

**Issue by Tim-Paik** [SagerNet/SagerNet#77]
**Is your feature request related to a problem? Please describe.**
在使用时时不时会手残上划杀死进程（强迫症），网络直接就断掉了
以及，如果软件不在后台运行，点控制中心的按钮是无效的，必须得重新从桌面打开SagerNet，这样的话控制中心按钮也没什么用了

**Describe the solution you'd like**
在设置中添加常驻后台选项、隐藏后台选项，开启后可以在后台被关闭时自启动，或者点击控制中心按钮自启动

**Describe alternatives you've considered**
目前没有

**Additional context**
我知道的有Scene4实现了在主界面返回可以隐藏后台运行emmm

感谢开发！

**Comment by nekohasekai** [comment]
检查系统设置
