### ISSUE TITLE
添加对SSH协议的支持

### ISSUE THREAD

**Issue by linuxblog996** [SagerNet/SagerNet#81]
**Is your feature request related to a problem? Please describe.**
我访问的一个网站里面有关于SSH协议连接的计划，我用别的类似的软件都没有这个功能

**Describe the solution you'd like**
添加SSH协议的支持

**Describe alternatives you've considered**
暂无

**Additional context**
暂无

**Comment by nekohasekai** [comment]
目前可能的实现是 connectbot 的 sshlib (但是需要jni 自由版本需要依赖一个很大的native library)
