### ISSUE TITLE
HTTPS代理添加Padding（填充）選項

### ISSUE THREAD

**Issue by dr9528** [SagerNet/SagerNet#92]
Naiveproxy電腦端自帶padding功能，iOS端shadowrocket的HTTPS代理也支持開啟padding，開啟padding可以緩解基於長度的流量分析，希望開發者考慮給HTTPS代理添加padding選項

**Comment by nekohasekai** [comment]
暂时未由 core 支持, 欢迎贡献.

**Comment by CalmLong** [comment]
有一个，不过是仅用于 VMess 的 TLS

https://t.me/v2msg/93

**Comment by dr9528** [comment]
既然有naive plugin了，普通HTTPS代理應該也不需要添加padding了，謝謝開發者
